### PR TITLE
Fix stock transfer date

### LINKED ISSUE #2081: Bad date for stock entry from transfert
When we enter a stock from transfer, the date of the entry is not considered; the movement of entry still has the date of exit.

The normal behavior is to have exit distinct to entry also in terms of dates.

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR : 
- fix the reception date for a stock transfer
- set a default description for a stock entry by a transfer

close #2081

### CODE REVIEW

File: server/controllers/stock/index.js [hunk 1]
```diff
@@ -236,7 +236,7 @@ function depotMovement(document, params) {
 
     isWarehouse = !!(parameters.from_depot_is_warehouse);
 
-    // track distribution to patient
+    // track distribution to other depot from a warehouse
```
Comment (jniles) [inline server/controllers/stock/index.js:239]: :dancer:

File: client/src/modules/stock/entry/entry.js [hunk 2]
```diff
@@ -331,7 +333,7 @@ function StockEntryController(
       from_depot : vm.movement.entity.instance.depot_uuid,
       to_depot : vm.depot.uuid,
       document_uuid : vm.movement.entity.instance.document_uuid,
-      date : vm.movement.entity.instance.date,
+      date : vm.movement.date,
```
Comment (jniles) [inline client/src/modules/stock/entry/entry.js:336]: :dancer:

Comment (jniles) [reply client/src/modules/stock/entry/entry.js:336]: Are you sure this bug doesn't affect other modules (exit)?  Or other entry types?

**Review by jniles — APPROVED** [review]
Looks fine to me :+1:
