### PR TITLE
refractor(employee registry) fix link to patient data

### LINKED ISSUE #4313: "Hospital Data" link on the Employee Registry is broken
It looks like the "hospital data" link in the employee registry broke at some point.  See below:
6ueofiyZtp

I am pretty sure this is supposed to link to the patient registry.

### PR DESCRIPTION
**Pull request by jeremielodi**
closes #4313

### CODE REVIEW

File: client/src/js/components/bhPatientFinancialActivity.js [hunk 1]
```diff
@@ -71,8 +71,6 @@ function PatientFinancialActivityCtrl(Patients, moment, Session, Constants) {
 
         $ctrl.dataMovement = dataMovement;
         $ctrl.noStockMovement = stockData.length === 0;
-      })
-      .finally(() => {
```
Comment (jniles) [inline client/src/js/components/bhPatientFinancialActivity.js:75]: Aah, I see you noticed the loading bug.  The actual problem isn't here.   If you want to fix it, change the `Promise.all()` at the beginning of this chain  to `$q.all()`.

AngularJS doesn't run the $digest loop after the `Promise()` but does after `$q()`.

**Review by jniles — COMMENTED** [review]
Looks good!  Just one comment on the $loading bit.

**Review by jniles — APPROVED** [review]
Thanks @jeremielodi !  Looks great to me.

bors r+
