### PR TITLE
bug(Stock Adjustment sort)

### LINKED ISSUE #5806: Stock Adjustment "quantity" column sorts alphabetically, not numerically
The stock adjustment "old quantity" column sorts alphabetically, not numerically.  It should be updated to allow us to properly order items.  Here is an example:

image

### PR DESCRIPTION
**Pull request by lomamech**
- Adding property type:number for sort column old quantity by
  numerically

closes #5806

### CODE REVIEW

File: server/lib/template/helpers/finance.js [hunk 1]
```diff
@@ -20,7 +20,15 @@ const EUR_FMT = {
   format : '%v&nbsp;%s', // value before symbol
 };
 
-const FORMATS = [null, FC_FMT, USD_FMT, EUR_FMT]; // NB: Indeces must match currency IDs in database
+const ROUBLE_FMT = {
```
Comment (jmcameron) [inline server/lib/template/helpers/finance.js]: Looks like this exchange rate testing code accidently got incorporated.  The PR should be updated to remove this.

**Review by jmcameron — COMMENTED** [review]
Please remove the unrelated testing code.

**Comment by jniles** [comment]
This is the correct fix.

bors r+
