### PR TITLE
fix(Trial Balance): disallow closed fiscal years

### LINKED ISSUE #1647: (bug) Closed Fiscal Years can still be written to and posted to the GL
A Fiscal Year that is closed can still have transactions written to it (in the Posting Journal) and subsequently posted to the General Ledger.

**Steps to reproduce**:
 1. Create a new Fiscal Year 2018
 2. Close the current Fiscal Year 2017
 3. Import balances into Fiscal Year 2018
 4. Make any caution payment in 2017 - note that it succeed without protest. (`/cash`)
 5. Navigate to the Posting Journal (`/journal`)
 6. Perform a Trial Balance on Fiscal Year 2017 - note that there are no errors thrown.
 7. Post to the GL.

**Expected Result(s)**:
 1. At the Cash Payments page, an error should be thrown that says "Fiscal Year is closed and cannot receive any more transactions.  Please confirm that your dates are correct or see the accountant."
 2. On the Trial Balance page, an error message should detail that all transactions within the Fiscal Year cannot be posted to the GL since the year is closed.

**Actual Result(s)**:
 1. Application performs as if no action had be taken regarding Fiscal Years.

It seems to me that the following rules should be in place:
 1. The Fiscal Year cannot be closed if there are open transactions in the Posting Journal.  This should be clearly stated by an error message.
 2. The Posting Journal should be able to be written to if there the Fiscal Year is closed.  This prevents a user from accidentally typing a closed year into a date input.  The error message should ask the user to confirm they have entered the correct date and then refer them to the accountant.
 3. The Trial Balance should date values that are outside of the current Fiscal Year and provide an error the the accountant.  If the accountant wants to proceed, they _must_ unlock the Fiscal Year first.

### PR DESCRIPTION
**Pull request by jniles**
This commit fixes a bug in the Trial Balance where closed fiscal years could still be posted to the GL.

Closes #1647.

### CODE REVIEW

File: server/models/procedures/trial_balance.sql [hunk 1]
```diff
@@ -50,6 +50,15 @@ BEGIN
     WHERE DATE(pj.trans_date) NOT BETWEEN DATE(p.start_date) AND DATE(p.end_date)
     GROUP BY pj.record_uuid;
 
+  -- check to make sure that the fiscal year is not closed
+  INSERT INTO stage_trial_balance_errors
+    SELECT pj.record_uuid, pj.trans_id, 'POSTING_JOURNAL.ERRORS.CLOSED_FISCAL_YEAR' AS code
+    FROM posting_journal AS pj JOIN stage_trial_balance_transaction AS temp
+      ON pj.record_uuid = temp.record_uuid
+      JOIN fiscal_year ON pj.fiscal_year_id = fiscal_year.id
+    WHERE fiscal_year.locked <> 0
```
Comment (mbayopanda) [inline server/models/procedures/trial_balance.sql:59]: 👍

**Review by mbayopanda — APPROVED** [review]
LGTM
