### PR TITLE
fix(stock report) correctly calculate sum when details are not displayed

### LINKED ISSUE #4384: Rapport de Sorties de Stock doesn't sum values correctly when details are not displayed
The Rapport de Sorties de Stock doesn't show the correct values if you hide the details.  My guess is that it is summing the unit costs instead of the total costs.  See below:
uv5XB1I8MP
_GIF 1: Different values depending on if details are shown or not_

### PR DESCRIPTION
**Pull request by jeremielodi**
closes #4384

### CODE REVIEW

File: server/controllers/stock/reports/stock/exit/exitToPatient.js [hunk 1]
```diff
@@ -12,7 +12,7 @@ function fetch(depotUuid, dateFrom, dateTo, showDetails) {
   const sql = `
   SELECT
     i.code, i.text, iu.text AS unit_text, BUID(m.document_uuid) AS document_uuid,
-    (m.quantity * m.unit_cost) AS cost, m.unit_cost,
+    SUM(m.quantity * m.unit_cost) AS cost, m.unit_cost,
```
Comment (mbayopanda) [inline server/controllers/stock/reports/stock/exit/exitToPatient.js:15]: 👍

**Review by mbayopanda — COMMENTED** [review]
I gues, you have also to apply this change in : 
- exitToService
- exitToLoss
- exitToDepot

**Review by mbayopanda — APPROVED** [review]
LGTM 👍 

bors r+
