### PR TITLE
fix: ensure sane accounts in test data

### LINKED ISSUE #4846: The build:db method builds a database that has title accounts with a balance
I ran `yarn build:db` and give a voucher created with the account "601 - ACHATS DE MARCHANDISES".   This is a title account.  We must update this so our test data is consistent with what is actually possible in BHIMA.  It should not be possible for a title account to have a balance.

image

### PR DESCRIPTION
**Pull request by jniles**
This commit ensures that we have sane accounts in our test dataset by changing a title account to an income account.

image

Also detects title accounts in the trial balance.

Closes #4846.

### CODE REVIEW

File: test/data.sql [hunk 1]
```diff
@@ -2930,10 +2930,10 @@ INSERT INTO `voucher_item` (`uuid`, `account_id`, `debit`, `credit`, `voucher_uu
   (HUID('90583c32-b1b2-11e8-9689-0b54421d0e49'), 187, 100, 0, @first_voucher, @first_invoice, HUID('2c6c48a2-b1b3-11e8-ae9b-1fa4024347ab')),
   (HUID('9317a11a-b1b2-11e8-93d6-b30828591803'), 182, 0, 100, @first_voucher, NULL, NULL),
   (HUID('941ae478-b1b2-11e8-9492-6385e74c37a0'), 188, 200, 0, @second_voucher, NULL, NULL),
-  (HUID('953defee-b1b2-11e8-ac16-3b802412d42d'), 200, 0, 200, @second_voucher, NULL, NULL),
+  (HUID('953defee-b1b2-11e8-ac16-3b802412d42d'), 242, 0, 200, @second_voucher, NULL, NULL),
   (HUID('97ad9a22-b1b2-11e8-acba-6b85fd27d57d'), 125, 300, 0, @third_voucher, @cash_payment, HUID('2f0b966c-b1b3-11e8-8dd2-1715a827ad9b')),
   (HUID('8ba0571a-b1b2-11e8-8688-fb9547361273'), 117, 0, 300, @third_voucher, NULL, NULL),
```
Comment (lomamech) [inline test/data.sql]: On this line, the account identifier 117 corresponds to that of the account [165 - Deposits and  Guarantees received]

**Review by lomamech — COMMENTED** [review]
Here is some transaction on the test database that uses title accounts
- TPC1 with Id 117 for [165 - Depots et Cautionnement recus]
- TPC1 with Id 125 for  [1861 - Comptes de liaison charges]
- TPA42 with 200 Id  [601 - ACHATS DE MARCHANDISES ]

I think it will also be necessary to revisit the accounts used in different Integrations and E2E tests
