### PR TITLE
fix(fee centers): do not show uuids

### LINKED ISSUE #4938: Hide UUIDs from the user in Distribution Center registry
Here is what the distribution center update page looks like:

image

We should update this page to replace the UUID with the transaction ID and hide the uuid from the client.  We don't show UUIDs anywhere else in the application and it doesn't make sense to show them here.

### PR DESCRIPTION
**Pull request by jniles**
Fixes the client to group by transaction ID, not UUID.  Also removes the selection from the grid.  Finally, it also adds a "view transactions" feature to allow users to quickly browse the linked transactions in the posting journal.

Closes #4938.

### CODE REVIEW

File: client/src/modules/distribution_center/update/update_center.js [hunk 1]
```diff
@@ -116,15 +113,14 @@ function UpdateCenterController(DistributionUpdateCenters, DistributionCenters,
     }],
   };
 
-  vm.grouping = new Grouping(vm.gridOptions, true, 'row_uuid', vm.grouped, true);
+  vm.grouping = new Grouping(vm.gridOptions, true, 'trans_id');
```
Comment (mbayopanda) [inline client/src/modules/distribution_center/update/update_center.js:116]: 👍

**Comment by jniles** [comment]
@mbayopanda can I get a review?

**Review by mbayopanda — APPROVED** [review]
LGTM 👍 

bors r+
