### PR TITLE
Fix voucher registry ESC press

### LINKED ISSUE #1073: (bug) Hitting "esc" on the voucher registry search button throws console error
The voucher registry (`#/vouchers`) allows a user to search for a date range.  However, this filter is buggy, and will throw a console error when dismissed with the ESC key.

**Steps to reproduce**
 1. Navigate to the voucher registry
 2. Click "search"
 3. Hit "ESC" on your keyboard.

**Expected Result**
The modal disappears, returning the user to the same grid as before the search button was clicked.

**Actual Result**
The loading indicator loads indefinitely, and the console throws an error.

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR fix : 
- console error when backdrop click or ESC press

Close #1073

### CODE REVIEW

File: client/src/partials/templates/modals/dateInterval.js [hunk 1]
```diff
@@ -22,7 +22,7 @@ function DateIntervalModalController (Instance) {
 
   // close
   function close() {
-    Instance.dismiss();
+    Instance.close();
```
Comment (jniles) [inline client/src/partials/templates/modals/dateInterval.js:25]: :+1:

**Review by jniles — APPROVED** [review]
LGTM.
