### PR TITLE
fix: migrate to utf8mb4

### LINKED ISSUE #2989: Remove collations from SQL queries
We have eight queries that manage character set collations themselves instead of using the database's globally defined collation.  This is making the upgrade process hard from MySQL's broken `utf8` to `utf8mb4`.   It would be ideal to remove these individual collation in favor of datbase, table, and column level collations. 

These queries probably ran into some issue with collations that resulted in errors.  The developer may have to debug these queries to see what the issue is.

Here they are, with line numbers:
managedcollations
_Fig 1: Queries with COLLATE_

(Found via `grep -nr "COLLATE"`)

### PR DESCRIPTION
**Pull request by jniles**
This commit migrates the database to UTF8MB4 in preparation for MySQL 8 which defaults to this.  It also produces better results for diverse character sets.

Closes #2989.

**Overview**
The motivation for this Pull Request is two-fold:
 1. Make sure no one had [break the server](https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434) by putting valid characters that [cannot be represented in MySQL's UTF8 character set](https://stackoverflow.com/questions/30074492/what-is-the-difference-between-utf8mb4-and-utf8-charsets-in-mysql#30074553).
 2. Ensure we are set up for future releases of MySQL and future languages by migrating to UTF8MB4.  MySQL 8 will support this out of the box.

And additional benefit continues the work started by @mbayopanda in his work on Travis CI changes in #3061 to document and standardize the character sets and collations in our database.  Previously, we just relied on having "the right set up", with some of our Stored Procedures in the server's default encoding, functions called in the mysqljs's default encoding, etc...  Now, we define at creation time and connection time the character sets and collations we are working with.

**Notes**
I had to [skip one test](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/test/end-to-end/verificationLinks/verificationLinks.spec.js#L19).  It was the link between debtor groups and patients.  I'm pretty sure this is due to the fact that the order data was inserted in changed somehow.  Either way, the test is non-specific and should be re-written to reference the group by its name.

### CODE REVIEW

**Comment by jniles** [comment]
@mbayopanda can I get a review?

**Comment by jmcameron** [comment]
If a separate manual step is necessary to upgrade the database (apart from those done automatically by 'yarn dev'), please make a note of that somewhere so I'll know what to do.   Thanks.

-Jonathan C

**Comment by jniles** [comment]
@jmcameron good point!  I'm not confident it works on anyone else's machine but my own (plus Travis), so I'm hoping @mbayopanda can help contribute those insights when he tests on Windows.  Once we are confident that it works with `yarn dev`, I'll jot down some notes to include with this PR.

File: server/lib/db/index.js [hunk 1]
```diff
@@ -32,7 +31,7 @@ class DatabaseConnector {
       user     : process.env.DB_USER,
       password : process.env.DB_PASS,
       database : process.env.DB_NAME,
-      charset  : 'utf8_unicode_ci',
+      charset  : 'UTF8MB4_UNICODE_CI',
```
Comment (mbayopanda) [inline server/lib/db/index.js]: 👍 it is important to comment that the charset `UTF8MB4_UNICODE_CI` must be in uppercase.

File: server/lib/db/index.js [hunk 2]
```diff
@@ -115,8 +114,8 @@ class DatabaseConnector {
   one(sql, params, id, entity = 'record') {
     return this.exec(sql, params)
       .then(rows => {
-        const errorMessage =
-          `Expected ${entity} to contain a single record with id ${id}, but ${rows.length} were found!`;
+        // eslint-disable-next-line max-len
```
Comment (mbayopanda) [inline server/lib/db/index.js:121]: 😄 is it allowed ?

File: server/models/functions.sql [hunk 3]
```diff
@@ -134,7 +134,7 @@ BEGIN
     SET accountType = 'expense';
   END IF;
 
-  SET accountTypeId = (SELECT id FROM account_type WHERE `type` = accountType COLLATE utf8_unicode_ci LIMIT 1);
+  SET accountTypeId = (SELECT id FROM account_type WHERE `type` = accountType COLLATE utf8mb4_unicode_ci LIMIT 1);
```
Comment (mbayopanda) [inline server/models/functions.sql]: Is it possible to get rid also of all these `COLLATE utf8mb4_unicode_ci` ?

File: server/models/procedures/account.sql [hunk 4]
```diff
@@ -28,31 +28,31 @@ BEGIN
   DECLARE IMPORT_DEFAULT_OHADA_ACCOUNT_OPTION TINYINT(1) DEFAULT 1;
 
   SET existAccount = (SELECT IF((SELECT COUNT(`number`) AS total FROM `account` WHERE `number` = accountNumber) > 0, 1, 0));
-  SET existAccountType = (SELECT IF((SELECT COUNT(*) AS total FROM `account_type` WHERE `type` = accountType COLLATE utf8_unicode_ci) > 0, 1, 0));
-  SET accountTypeId = (SELECT id FROM `account_type` WHERE `type` = accountType COLLATE utf8_unicode_ci LIMIT 1);
+  SET existAccountType = (SELECT IF((SELECT COUNT(*) AS total FROM `account_type` WHERE `type` = accountType COLLATE utf8mb4_unicode_ci) > 0, 1, 0));
+  SET accountTypeId = (SELECT id FROM `account_type` WHERE `type` = accountType COLLATE utf8mb4_unicode_ci LIMIT 1);
```
Comment (mbayopanda) [inline server/models/procedures/account.sql]: If we can remove all these `COLLATE utf8mb4_unicode_ci` it will be very nice

File: sh/build-database.sh [hunk 5]
```diff
@@ -16,38 +16,38 @@ set +a
 TIMEOUT=${BUILD_TIMEOUT:-8}
 
 # build the test database
-mysql -u $DB_USER -p$DB_PASS -e "DROP DATABASE IF EXISTS $DB_NAME ;" &> /dev/null
```
Comment (mbayopanda) [inline sh/build-database.sh]: Why don't we redirect the output to `/dev/null` now ?

File: test/end-to-end/verificationLinks/verificationLinks.spec.js [hunk 6]
```diff
@@ -16,7 +16,7 @@ describe('Check Inter-Registry Links', () => {
     GU.expectRowCount('patient-registry', 2);
   });
 
-  it('Checks the link between Debtor Groups -> Patient Registry', () => {
+  it.skip('Checks the link between Debtor Groups -> Patient Registry', () => {
```
Comment (mbayopanda) [inline test/end-to-end/verificationLinks/verificationLinks.spec.js]: Could you leave a comment about the reason of skipping this test ?

**Review by mbayopanda — APPROVED** [review]
LGTM 👍 

I leave some comments which cannot block the merge this PR

File: server/lib/db/index.js (hunk 1 above)
Comment (jniles) [reply server/lib/db/index.js]: True.  Will do.

File: server/models/functions.sql (hunk 3 above)
Comment (jniles) [reply server/models/functions.sql]: Hmm... good question.  Let me try!

File: server/lib/db/index.js (hunk 2 above)
Comment (jniles) [reply server/lib/db/index.js:121]: Eh, it's either that or figure our a shorter representation ;)

File: sh/build-database.sh (hunk 5 above)
Comment (jniles) [reply sh/build-database.sh]: Ah - this was a feature requested by @jmcameron.  We basically eliminate all ability to debug by sending all errors into `/dev/null/`.  I figured this was a bit too much.  Do you think we should put it back?

Comment (jmcameron) [reply sh/build-database.sh]: Can we set up the script to have an argument that determines whether the output goes to /dev/null or to regular output?

Comment (jmcameron) [reply sh/build-database.sh]: If you want, I can take a cut at setting up the script with an optional argument for debugging:

  sh/build-database.sh debug

would force output to output to go to stdout (if I can figure out how to do that...)

-Jonathan C

Comment (jmcameron) [reply sh/build-database.sh]: Got a test bash script working for the debug option here.

Comment (jmcameron) [reply sh/build-database.sh]: [testo.txt](https://github.com/IMA-WorldHealth/bhima-2.X/files/2336072/testo.txt)

Download, remove .txt and chmod +x and try it with:
   ./testo
   ./testo debug

Comment (jniles) [reply sh/build-database.sh]: Hey, that is kind of nice!  I'll incorporate it. 👍

**Comment by jniles** [comment]
@mbayopanda, this is ready for a second review.

**Comment by jniles** [comment]
@sfount want to weigh in here?  Did you test it locally?

**Comment by sfount** [comment]
@jniles I've tested this branch locally and it passes all tests. Running the most up to date version of MySQL 5.6 on linux.

**Comment by jniles** [comment]
@sfount, thanks for you feedback.  Glad this didn't break anything!

**Comment by jniles** [comment]
Alright, merging!

bors r+

**Comment by jniles** [comment]
@jmcameron - to answer your earlier question: it's a long an laborious process and depends a lot on the database.  [This SO answer is a good overview](https://dba.stackexchange.com/questions/8239/how-to-easily-convert-utf8-tables-to-utf8mb4-in-mysql-5-5#21684) of the basic procedure, to be adapted to whatever databases are needed.  Additionally, the Stored Procedures and Functions may have to be recreated in a connection whose CHARSET is utf8mb4 for the parameters to be correct.

For our production sites, we'll need to write a custom script to migrate their datasets.  Since we don't have a standard way of pushing updates, we'll need to write scripts for each site's database in particular.

EDIT:
[Percona](https://www.percona.com/blog/2018/04/10/migrating-database-charsets-to-utf8mb4/) has a great article on migrating existing databases in a sane fashion.  Depends on our hardware though.
