### PR TITLE
fix(report): aged debtor bugs

### LINKED ISSUE #924: Reports using Enterprise currency
This issue is to track ensuring all reports are provided in the enterprises set currency. 

**Required refactors**
- [x] Patient Invoice
- [ ] Cashflow (Requires controller refactor/ simplification for future maintenance) 
- [x] Patient financial activity
- [x] Customer Debts
- [x] Income vs. Expense 
- [x] Accounts Report

### PR DESCRIPTION
**Pull request by jniles**
This commit replaces the aged debtors report with the original aged
debtors report.  The second aged report was buggy and had ill-defined
behavior.  The second one has been vetted and includes saner defaults.

Partially fixes #924.

----
Thank you for contributing!

Before submitting this pull request, please verify that you have:
 - [x] Run your code through JSHint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
 - [x] Run integration tests.
 - [x] Run end-to-end tests.
 - [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

**Comment by jniles** [comment]
@sfount, can I get a review?

File: server/controllers/finance/reports/debtors/index.js [hunk 1]
```diff
@@ -69,21 +68,24 @@ function agedDebtorReport(req, res, next) {
...
+      SUM(IF(DATEDIFF(?, gl.trans_date) BETWEEN 60 AND 90, gl.debit_equiv - gl.credit_equiv, 0)) AS ninety,
+      SUM(IF(DATEDIFF(?, gl.trans_date) > 90, gl.debit_equiv - gl.credit_equiv, 0)) AS excess,
       SUM(gl.debit_equiv - gl.credit_equiv) AS total
     FROM debtor_group AS dg JOIN debtor AS d ON dg.uuid = d.group_uuid
       LEFT JOIN general_ledger AS gl ON gl.entity_uuid = d.uuid
     ${includeZeroes ? '' : havingNonZeroValues}
   `;
 
+  // format the dates for MySQL escape
+  const dates = _.fill(Array(4), new Date(qs.date));
```
Comment (sfount) [inline server/controllers/finance/reports/debtors/index.js:82]: Cool :+1:

**Review by sfount — APPROVED** [review]
I think we should formally favour using SQL to groupings and calculations on reports. A database is designed to do these type of operations and once the queries have been designed they are must less likely to have corner cases. This looks like a good improvement.
