### PR TITLE
fixing 500 error in patient last invoice

### LINKED ISSUE #689: (bug) Newly registered patient throws 500 error for latest invoice
If a new patient is registered then viewed in the Patient Registry, the console shows a 500 error.  If there is indeed some error, there should be a `Notify.handleError()` call.

**Steps to Reproduce**
1. Register a patient with the debtor group `First Test Debtor Group` and the patient group `HIV patients`.
2. Navigate to the Patient Registry and click on the patient record.

**Expected Result**: The console should be clean or a `handleError()` danger message should appear.
**Actual Result**: The console shows a HTTP 500 error for `/patients/:uuid/invoices/latest`.

### PR DESCRIPTION
**Pull request by DedrickEnc**
This PR closes #689 

Thank you for contributing!

Before submitting this pull request, please verify that you have:
- [x] Run your code through JSHint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
- [x] Run integration tests.
- [x] Run end-to-end tests.
- [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

File: client/src/partials/patients/registry/registry.js [hunk 1]
```diff
@@ -2,15 +2,15 @@ angular.module('bhima.controllers')
...
-  'PatientService', 'NotifyService', 'moment', 'AppCache', 'util', 'ReceiptModal'
+  'PatientService', 'NotifyService', 'AppCache', 'util', 'ReceiptModal'
 ];
 
 /**
  * Patient Registry Controller
  *
  * This module is responsible for the management of Patient Registry.
  */
-function PatientRegistryController(Patients, Notify, moment, AppCache, util, Receipts) {
```
Comment (jniles) [inline client/src/partials/patients/registry/registry.js:13]: :dancer:

File: server/controllers/medical/patients/index.js [hunk 2]
```diff
@@ -668,23 +671,25 @@ function latestInvoice (req, res, next) {
...
-      uid             : invoices[0].uid,
-      reference       : invoices[0].reference,
-      credit          : invoices[0].credit,
-      debit           : invoices[0].debit,
-      balance         : invoices[0].balance,
-      entity_uuid     : invoices[0].entity_uuid,
-      invoicesLength  : invoicesLength[0].invoicesLength
-    };
-
+    var numberPayment = payments ? payments[0].numberPayment : 0; //what is his meaning?
```
Comment (jniles) [inline server/controllers/medical/patients/index.js]: Good question!  A comment probably would have been nice ...

File: server/controllers/medical/patients/index.js [hunk 3]
```diff
@@ -668,23 +671,25 @@ function latestInvoice (req, res, next) {
...
+    if(invoices && invoicesLength){
```
Comment (jniles) [inline server/controllers/medical/patients/index.js]: Hmm.  Instead of trying to manipulate this current promise chain, it would be cleaner to separate the logic into a helper function.  Like this:

``` js
function latestInvoice(req, res, next) {
  // declare variables, etc..

  return db.exec(sql, [uid])
    .then(rows => {
      let hasLatestInvoice = rows.length > 0;
      let latestInvoice = rows[0];

      // fake promise to simply skip the latest invoice loading.
      let skip = q({});  

      return hasLatestInvoice ?
        loadLatestInvoice(latestInvoice) : 
        skip;
    })
    .then(res => {
      res.status(200).json(invoice);
    })
    .catch(next)
    .done();
});

function loadLatestInvoice(invoice) {
   // in this function, do the db.exec().spread(...);
}
```

Does that make sense?  Then you will not be forced to write `db.exec(sql, [null, null, null])` and make the database/server do unnecessary work.

File: client/src/js/components/bhLatestInvoice.js [hunk 4]
```diff
@@ -27,7 +27,7 @@ function LatestInvoice(Patient, moment) {
 
   /** getting patient document */
   function startup() {
-    if (!vm.debtorUuid) { return; }
+    if (!vm.debtorUuid || !vm.patientInvoice) { return; }
```
Comment (jniles) [inline client/src/js/components/bhLatestInvoice.js]: Isn't `vm.patientInvoice` always undefined at the beginning of the code?  When does it become defined?  It looks like this code will never run past this function...

**Comment by jniles** [comment]
@dedrickenc, I have finished a review.

It's always easier to break promise chains into pieces, as I have proposed here.  Let me know if it is confusing and we can discuss.  Otherwise, I await your feedback/changes.

**Comment by DedrickEnc** [comment]
@jniles

File: server/controllers/medical/patients/index.js [hunk 5]
```diff
@@ -653,40 +634,65 @@ function latestInvoice (req, res, next) {
...
+        uid             : invoices[0].uid,
+        reference       : invoices[0].reference,
+        credit          : invoices[0].credit,
+        debit           : invoices[0].debit,
+        balance         : invoices[0].balance,
+        entity_uuid     : invoices[0].entity_uuid,
+        invoicesLength  : invoicesLength[0].invoicesLength
+      };
+
+      console.log('invoice finale', invoice);
```
Comment (jniles) [inline server/controllers/medical/patients/index.js]: Just  a couple of `console.log`s.

**Comment by jniles** [comment]
@DedrickEnc, just a couple of `console.log()`s to fix, otherwise the code LGTM.  Thanks!

**Comment by DedrickEnc** [comment]
@jniles 
Done!

**Comment by jniles** [comment]
LGTM :+1:
