### PR TITLE
fix(invoices): only show item error if configured

### LINKED ISSUE #1046: (Bug) Invoice item has no inventory assigned alert always shows during creation of invoice
An alert informing the user that not all of the invoice items have been fully configured is constantly shown throughout the invoice creation process. 

This should only be shown once the user has tried to submit the invoice or presented in another way. 

**Incomplete Invoice - should not be presented as an error state**
screenshot 2016-12-12 at 09 40 01

### PR DESCRIPTION
**Pull request by jniles**
This commit ensures that the global error message is only shown if there
is no sales account _after_ the item has been configured.  Previously,
this resulted in showing large error messages during perfectly normal
operation.

Closes #1046.

hiddenerrorswheninvoicenotconfigured
_Fig 1: Hidden Errors when Items not Configured_

visibleerrorswheninvoiceconfigured
_Fig 2: Visible Errors when Items missing Sales Account)_

------
Thank you for contributing!

Before submitting this pull request, please verify that you have:
 - [x] Run your code through JSHint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
 - [x] Run integration tests.
 - [x] Run end-to-end tests.
 - [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

File: client/src/js/services/PatientInvoiceForm.js [hunk 1]
```diff
@@ -157,8 +157,9 @@ function PatientInvoiceFormService(Patients, PriceLists, Inventory, AppCache, St
     var invalidItems = this.store.data.filter(function (row) {
       row[ROW_ERROR_FLAG] = highlight ? row._invalid : false;
 
-      // this sets the global configuration error if a
-      if (!row._hasSalesAccount) {
+      // this sets the global configuration error if there is no sales account
+      // and the row has already been configured.
+      if (row._initialised && !row._hasSalesAccount) {
```
Comment (sfount) [inline client/src/js/services/PatientInvoiceForm.js:162]: 👍

**Review by sfount — APPROVED** [review]
This will result in a much clearer UX.
