### PR TITLE
fix(journal): Allow deletion of transaction in the journal

### LINKED ISSUE #2510: Allow deleting a transaction from the transaction edit modal
There needs to be a button on the "edit transaction" form that allows you to delete the transaction.  Since we support deletion through a [uniform API](https://github.com/IMA-WorldHealth/bhima-2.X/pull/2286), it should be trivial to add this.

The basic design is this:
 1. Add a button `btn-danger` that says "delete transaction" to the TransactionEditModal.  It should probably be below the transaction's grid, but not on the footer.
 2. Call `TransactionService.remove(uuid)` with the `record_uuid` of the transaction.
 3. Close the modal when it is successfully removed.

### LINKED ISSUE #2511: If a transction is made in a currency, use that currency for the editing
Currently, we allow a user to edit a transactions `debit_equiv` and `credit_equiv` values directly in the Posting Journal.  This changes the _value_ of the transaction in the enterprise currency.  We then [convert those values on the server](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/server/controllers/finance/journal/index.js#L451) into the correct debit/credit values.

As our clients in HEV noted, this is backwards.  If a user makes a mistake in a non-enterprise currency, they want to correct _that value_ and not the enterprise's currency.

For example, imagine that you are running an enterprise in FC and you have a bill for $50.  By accident, you type $500 in the voucher.  When you try to edit this, you will be editing the FC value of `exchange_rate * 500` instead of what you originally mis-typed of $500.   This makes it really confusing to fix.

I propose the following:
 1. If you made a transaction in a particular currency, it should be displayed for editing in that currency.  If the currency is not the enterprise currency, you should also show the exchange rate.
 2. Once the transaction is saved, you should convert it into the enterprise currency.

In this way, it is the application itself that does the exchange rate math, not the user.  That's just silly.

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR : 
- Allow to delete a transaction in the journal via the edit transaction modal
- Edit transaction debit and credit, not the converted amounts

Close #2510 
Close #2511

### CODE REVIEW

File: client/src/js/components/bhExchangeRate.js [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+ * @overview bhExchangeRate
+ *
+ * @description
+ * This component allows to display the exchange rate
+ */
+angular.module('bhima.components')
+  .component('bhExchangeRate', {
+    templateUrl : 'modules/templates/bhExchangeRate.tmpl.html',
+    controller : bhExchangeRateController,
+    controllerAs : '$ctrl',
```
Comment (jniles) [inline client/src/js/components/bhExchangeRate.js:11]: Just FYI - I believe all components default to `$ctrl` for their `controllerAs`.

File: client/src/modules/journal/modals/editTransaction.modal.js [hunk 2]
```diff
@@ -335,28 +356,49 @@ function JournalEditTransactionController(
...
+        const deleteTransactionResult = {
+          deleted : true,
+          removed : getGridRowsUuid(),
+        };
+        Modal.close(deleteTransactionResult);
+      });
+  };
+
+  function getGridRowsUuid() {
+    return vm.rows.data.map((row) => {
```
Comment (jniles) [inline client/src/modules/journal/modals/editTransaction.modal.js:384]: Alternatively: `vm.rows.data.map(row => row.uuid);`.

File: client/src/modules/journal/modals/editTransaction.modal.js [hunk 3]
```diff
@@ -335,28 +356,49 @@ function JournalEditTransactionController(
...
+      return row.uuid;
+    });
+  }
+
   // rows - array of rows
   // uuids - array of uuids
   function filterRowsByUuid(rows, uuids) {
-    var result = rows.filter(function (row) {
+    const result = rows.filter((row) => {
```
Comment (jniles) [inline client/src/modules/journal/modals/editTransaction.modal.js:392]: Alternatively, `return rows.filter(row => contains(uuids, row.uuid));`.

File: client/src/modules/templates/bhExchangeRate.tmpl.html [hunk 4]
```diff
@@ -0,0 +1,12 @@
+<span >
+  <span translate>FORM.LABELS.EXCHANGE_RATE</span> : 
+  <b ng-show="$ctrl.isFirstCurencyLabel">
+    1{{$ctrl.primaryExchange.symbol}} = {{ $ctrl.primaryExchange.rate | limitTo:$ctrl.EXCHANGE_RATE_DISPLAY_SIZE }}
+    ({{ $ctrl.enterprise.currencySymbol }})
+  </b>
+
+  <b ng-show="!$ctrl.isFirstCurencyLabel">
```
Comment (jniles) [inline client/src/modules/templates/bhExchangeRate.tmpl.html:8]: Currency should have two "r"s. :)

File: client/src/modules/templates/modals/confirmDialog.modal.html [hunk 5]
```diff
@@ -1,20 +1,16 @@
 <form name="ConfirmDeletion" ng-submit="$ctrl.accept(ConfirmDeletion)" novalidate>
 
   <div class="modal-header">
-    <button ng-click="$ctrl.close()" type="button" class="close">&times;</button>
-    <h4>
-      {{ "FORM.DIALOGS.SURE_CONTINUE" | translate }}
```
Comment (jniles) [inline client/src/modules/templates/modals/confirmDialog.modal.html:6]: Nice refactors!

File: client/src/modules/templates/modals/confirmDialog.modal.js [hunk 6]
```diff
@@ -9,35 +9,33 @@ ConfirmDialogModalController.$inject = ['$uibModalInstance', '$translate', 'data
  * This controller is responsible for check a match text given to continue
  * with an action
  */
-function ConfirmDialogModalController (Instance, $translate, Data) {
-  var vm = this;
+function ConfirmDialogModalController(Instance, $translate, Data) {
+  const vm = this;
```
Comment (jniles) [inline client/src/modules/templates/modals/confirmDialog.modal.js:13]: 👍

File: client/src/modules/templates/modals/confirmDialog.modal.js [hunk 7]
```diff
@@ -9,35 +9,33 @@ ConfirmDialogModalController.$inject = ['$uibModalInstance', '$translate', 'data
...
     // make sure the modal isn't accidentally called with empty values
     if (!Data.pattern || !Data.patternName) {
-      throw new Error(
-        'ConfirmDialogModal requires both a pattern and an element name to be defined, but received:' +
-        'data.pattern = ' + Data.pattern + ' ' +
-        'data.patternName = ' + Data.patternName
-      );
+      throw new Error(`
+        ConfirmDialogModal requires both a pattern and an element name to be defined, but received: 
+        data.pattern = ${Data.pattern} and data.patternName = ${Data.patternName}
```
Comment (jniles) [inline client/src/modules/templates/modals/confirmDialog.modal.js:33]: 💃

File: client/src/modules/templates/modals/confirmDialog.modal.js [hunk 8]
```diff
@@ -55,13 +53,13 @@ function ConfirmDialogModalController (Instance, $translate, Data) {
...
 
-    var result = isMatching(vm.pattern, vm.text);
+    const result = isMatching(vm.pattern, vm.text);
 
     if (!form.$invalid && result) {
       Instance.close(result);
     } else if (!form.$invalid && !result) {
       vm.noCorrespondancy = $translate.instant('FORM.DIALOGS.NO_CORRESPONDANCY')
-        .concat(' "', vm.text, '"');
+        .concat(` "${vm.text}" `);
```
Comment (jniles) [inline client/src/modules/templates/modals/confirmDialog.modal.js:62]: 👯‍♂️

File: server/controllers/finance/journal/index.js [hunk 9]
```diff
@@ -469,6 +474,27 @@ function transformColumns(rows, newRecord, transactionToEdit, setFiscalData) {
       });
     }
 
+    if (row.debit) {
```
Comment (jniles) [inline server/controllers/finance/journal/index.js:477]: Nice!

File: client/src/js/components/bhExchangeRate.js [hunk 10]
```diff
@@ -0,0 +1,68 @@
...
+  });
+
+bhExchangeRateController.$inject = [
+  'CurrencyService', 'ExchangeRateService', 'SessionService',
+  'NotifyService', 'moment',
+];
+
+function bhExchangeRateController(Currencies, Rates, Session, Notify, Moment) {
+  var $ctrl = this;
```
Comment (jniles) [inline client/src/js/components/bhExchangeRate.js:20]: This could be a `const` :)

File: client/src/js/components/bhExchangeRate.js [hunk 11]
```diff
@@ -0,0 +1,68 @@
...
+
+  $ctrl.today = new Date();
+  $ctrl.primaryExchange = {};
+  $ctrl.enterprise = Session.enterprise;
+  $ctrl.EXCHANGE_RATE_DISPLAY_SIZE = 6;
+
+  /*
+    $ctrl.isFirstCurencyLabel is used to check the exchange Rate
```
Comment (jniles) [inline client/src/js/components/bhExchangeRate.js:28]: Great comment!

File: client/src/js/components/bhExchangeRate.js [hunk 12]
```diff
@@ -0,0 +1,68 @@
...
+        $ctrl.currencies = currencies.filter((currency) => {
+          return currency.id !== Session.enterprise.currency_id;
+        });
+
+        // load supported rates
+        return Rates.read(true);
+      })
+      .then(() => {
+        $ctrl.currencies.forEach((currency) => {
+          currency.rate = Rates.getCurrentRate(currency.id);
```
Comment (jniles) [inline client/src/js/components/bhExchangeRate.js:47]: Is this the same code used on the home page?  If so, we should probably put it in a service ... something like `Exchange.getHumanReadableRate()`.

File: client/src/modules/journal/journal.js [hunk 13]
```diff
@@ -551,50 +550,71 @@ function JournalController(
...
+      // rows have been added, we have no guarantees on filters so display a warning
+      vm.unknownTransactionEditState = true;
+    }
+    vm.gridApi.grid.notifyDataChange(uiGridConstants.dataChange.ALL);
+
+    Notify.success('POSTING_JOURNAL.SAVE_TRANSACTION_SUCCESS');
+  }
+
+  // Handle Delete Transaction Result
+  function handleDeleteTransactionResult(deleteSessionResult) {
```
Comment (jniles) [inline client/src/modules/journal/journal.js:607]: Nice separation.  Very readable. 👍

File: client/src/modules/journal/modals/editTransaction.modal.html [hunk 14]
```diff
@@ -109,13 +115,16 @@
...
 
 <div class="modal-footer clearfix">
-  <!-- informational: this record has been edited x times  -->
-  <span ng-if="ModalCtrl.hasPreviousEdits" class="text-muted pull-left" style="margin-top:5px;">
-    <i class="fa fa-info-circle"></i>
-    <span translate translate-values="ModalCtrl.lastEditValues">POSTING_JOURNAL.HAS_PREVIOUS_EDITS</span>
-  </span>
+  <button
+    class="btn btn-danger pull-left" 
+    ng-if="!ModalCtrl.readOnly"
```
Comment (jniles) [inline client/src/modules/journal/modals/editTransaction.modal.html:120]: Nice 👍

File: client/src/modules/journal/modals/editTransaction.modal.js [hunk 15]
```diff
@@ -231,14 +252,14 @@ function JournalEditTransactionController(
 
 
   function verifyEditableTransaction(transaction) {
-    var posted = transaction[0].posted;
+    const { posted } = transaction[0];
```
Comment (jniles) [inline client/src/modules/journal/modals/editTransaction.modal.js:255]: 💃

**Review by jniles — APPROVED** [review]
Works really well for me!  Great work!

A couple of things for us to work on in the future:
 1. Simultaneously updating the `debit` and `debit_equiv` of a transaction doesn't make sense ... we should block it with an error on the server.  Same goes for `credit` and `credit_equiv`.
 2. If we use the same blocks of code for exchange rate, we should move it into a service.  That way we reuse the maximum code possible.

These are important changes.  The code looks really good!

bors r+
