### PR TITLE
fix(install): add enterprise settings

### LINKED ISSUE #2761: bug(invoicing): the invoice module is broken with init database
The invoice module is broken when we use the init database for a fresh instance of bhima.

invoicing

### PR DESCRIPTION
**Pull request by jniles**
This commit adds configuration of the enterprise settings to the installation script.

Closes #2761.

### CODE REVIEW

File: server/controllers/install.js [hunk 1]
```diff
@@ -100,21 +100,29 @@ exports.proceedInstall = (req, res, next) => {
       delete _user.repassword;
     }
 
+    // default values for enterprise settigns
+    const enterpriseSetting = { enterprise_id : ENTERPRISE_ID };
```
Comment (mbayopanda) [inline server/controllers/install.js:104]: 👍

**Review by mbayopanda — APPROVED** [review]
LGTM 

bors r+
