### PR TITLE
fix(Column configuration limits length of visible columns)

### LINKED ISSUE #1759: bug: Column Configuration limits length of visible columns to 3
The Column Configuration modal isn't very portable since it doesn't know how to filter out special ui-grid plugin columns.  It should filter those out first, and then warn the user about selecting less than 1 column.

### PR DESCRIPTION
**Pull request by lomamech**
Update column hasEnoughColumns
- change default value column set 1
- Update structure alternative check if the firth and second element of ui
  grid are visible for the incrementation of defaultValueColumn

closes #1759

### CODE REVIEW

File: client/src/js/services/grid/GridColumns.js [hunk 1]
```diff
@@ -114,18 +114,19 @@ function GridColumnService(uiGridConstants, AppCache, Modal, util, $timeout) {
...
       /**
-        *This alternative structure checks if the first element of the grid is visible or not,
-        *finally to reinitialize the number of column by default
+        *This alternative structure checks if selectionRowHeaderCol or treeBaseRowHeaderCol are visible or not,
+        *finally to incremente the number of column by default
       */
-      if((column.name === "treeBaseRowHeaderCol") && !visible){
-        defaultValueColumn--;
+
+      if((column.name === "selectionRowHeaderCol" || column.name === "treeBaseRowHeaderCol") && visible){
```
Comment (jniles) [inline client/src/js/services/grid/GridColumns.js:128]: This is the correct way to do this :+1:

Comment (jniles) [reply client/src/js/services/grid/GridColumns.js:128]: Do you have eslint installed? I think it asks for a space between the `if` and the `(`.  Like this:
```js
if (x) {
  // something
}
```

The reason is to try and separate function calls and control flow code.  It makes it easy for a programmer (without syntax highlighting) to realize at a glance that `if` is not a function call - it is a control flow statement.

**Review by jniles — APPROVED** [review]
LGTM. I haven't tested this, but it's definitely the correct approach.  :+1:
