### PR TITLE
Fix lost asset serial numbers in stock entry for shipments

### LINKED ISSUE #6720: Fix bug about losing asset serial number in stock entry
When doing stock entry for assets via shipments, the serial number seems to be lost when you examine the incoming lots.

### PR DESCRIPTION
**Pull request by jmcameron**
Fixes a bug in transferring assets using the Shipments interface where the serial_number was being lost during the stock entry phase.

Closes https://github.com/IMA-WorldHealth/bhima/issues/6720

**TESTING**
- Use bhima_test
- Go to the shipments registry:  Shipments > Shipment Registry
   - Note the lot name and serial number for the motorcycle to use in the next step
   - Create a shipment to transfer the selected motorcycle (code = MOT...) from the Primary Depot to the secondary Depot.
   - Use the action menu for the new shipment to mark is as ready to ship
   - Use the action menu for the new shipment to do the stock exit
   - Use the action menu for the new shipment to do the stock entry
      - BEFORE clicking [Submit] to complete the stock entry, click on the link to the **Lots** for the lot (asset)
      - Verify that the original serial number is still present
      - Close the lots update modal
      - Click on the main [Submit] to complete the stock entry
- In the shipments registry
   - Verify that the serial number of the selected asset is unchanged

### CODE REVIEW

File: client/src/modules/stock/entry/entry.js [hunk 1]
```diff
@@ -515,6 +515,7 @@ function StockEntryController(
           isValid : true,
           lot : items[index].label,
           quantity : item.quantity,
+          serial_number : items[index].serial_number,
```
Comment (mbayopanda) [inline client/src/modules/stock/entry/entry.js:518]: 👍🏽

**Review by mbayopanda — APPROVED** [review]
Thank you @jmcameron 

bors r+
