### PR TITLE
Fix function to merge patients

### LINKED ISSUE #5217: Merge patients missing database updates
The Merge Patient function does many of the correct database updates for merging patients but is missing a few items:

- stock_movement (entity_uuid)
- medical_sheet (patient_uuid)
- entity_group_entity (entity_uuid)
- voucher_item (entity_uuid)
- stock_assignment (entity_uuid)
- entity (uuid)  (row needs to be deleted)

NOTE: The schema.sql file should be updated to indicate what each occurance of 'entity_uuid' can refer to (for example, see 'entity_uuid' in the 'stock_movement' table).

### PR DESCRIPTION
**Pull request by jmcameron**
This fix updates the server function to merge patients to take care of several database updates that were missed before.   The missing updates are described in Issue https://github.com/IMA-WorldHealth/bhima/issues/5217.   A few other fixes are added in this PR.

**SUGGESTIONS FOR BASIC TESTING**

- Use the IMCK database
- yarn dev
- Go to the Hospital > Patient Registry page
- Search for any patient name (eg, try "Tshiamua Mamba").   
- Click on the Name field on the top to make sure similar names are together
- Select the two patients that seem to be duplicates.
- Under the main menu, pick "Merge Patients"
- Select the one you want to keep and press the [Merge Patients] button
- When you get back to the Patient Registry page, note that only one of the two selected patients exists any longer.

**TO VERIFY DATABASE UPDATES**
- Use the IMCK database
- Use the attached script
- Use the procedure above to find duplicate patients
- Copy the full full name and hospital file number to a file on your computer
- Edit the attached script and insert the full name into the first query (rename to check_updates.sql)
  [check_updates.sql.txt](https://github.com/IMA-WorldHealth/bhima/files/5669301/check_updates.sql.txt)
- Run mysql with the IMCK database selected
- Execute in mysql:  **source check_updates.sql**
- Copy the puid (patient_uuid) and edit the check_updates.sql file to insert the puid and duid values into the SET @ commands. Make sure you get the puid and duid of the patient that you want to DELETE.
- Edit the script and remove the comments on lines after 24
- Run the script again and notice that some of the queries are finding matching records.
- Do the procedure above to delete the duplicate patient.
- Re-run the mysql script again and notice that all the checking queries find no matches.

### CODE REVIEW

File: server/controllers/medical/patients/merge.js [hunk 1]
```diff
@@ -71,10 +71,10 @@ router.post('/', async (req, res, next) => {
   const getSelectedDebtorUuid = `SELECT debtor_uuid FROM patient WHERE uuid = ?`;
   const getOtherDebtorUuids = `SELECT debtor_uuid FROM patient WHERE uuid IN (?)`;
 
-  const replaceDebtorInJournal = `
+  const replaceDebtorInPostingJournal = `
```
Comment (jniles) [inline server/controllers/medical/patients/merge.js:74]: :+1:

File: server/controllers/medical/patients/merge.js [hunk 2]
```diff
@@ -104,13 +114,25 @@ router.post('/', async (req, res, next) => {
...
+    UPDATE stock_movement SET entity_uuid = ? WHERE entity_uuid IN (?);
+  `;
 
   const removeOtherDebtors = `
     DELETE FROM debtor WHERE uuid IN (?);
   `;
   const removeOtherPatients = `
     DELETE FROM patient WHERE uuid IN (?);
   `;
+  const removeOtherEntities = `
```
Comment (jniles) [inline server/controllers/medical/patients/merge.js:130]: Despite the identical name, I don't think this `entity` table or the `entity_group` table has anything to do with the patient/entity_map/debtor tables.  I believe it is only concerned with emails.  That is, unless you have some information where a debtor_uuid showed up in the entity table, which would surprise me!

This being said, it won't harm anything having this in at the moment.  This is a non-blocking comment.

We should probably rename them to contacts and contact_group like the translated client-side calls them.

**Review by jniles — APPROVED** [review]
Tested this and it works really well.  That SQL file was clear and helpful, and I followed along easily.

bors r+
