### PR TITLE
fix(Fee Centers): proper currency rendering

### LINKED ISSUE #4437: Distribution Fee Center should show the correct currency for the transaction
Here is an example transaction imported via the Distribution Fee Center module. 
image

These values are in (potentially different) currencies.  We should make this clear by putting the currency symbols on the values.

### PR DESCRIPTION
**Pull request by jniles**
Adds in the appropriate currency rendering for the columns of the Distribution Fee Center.

Closes #4437.

image

### CODE REVIEW

File: client/src/modules/distribution_center/distribution_center.js [hunk 1]
```diff
@@ -83,8 +84,8 @@ function DistributionCenterController(DistributionCenters, Notify, uiGridConstan
         headerCellFilter : 'translate',
         cellClass : 'text-right',
         footerCellClass : 'text-right',
-        cellFilter : 'number: 2',
-        footerCellFilter : 'number:2',
+        cellFilter : 'currency:row.entity.currency_id',
```
Comment (mbayopanda) [inline client/src/modules/distribution_center/distribution_center.js:87]: 👍

**Review by mbayopanda — APPROVED** [review]
LGTM 👍 

bors r+
