### PR TITLE
fix(cash): alert when no invoices are selected

### LINKED ISSUE #772: (bug) Cash Payments shouldn't make an HTTP request if there are no cash items
The Cash Payments page is fairly complex since it deals with both Cautions and Cash Payments against invoices.  The current implementation does not block Cash Payment requests from submitting if there are no cash items (though the server rejects them).  We can do better by blocking the submit before it even sends an HTTP request and create an error message that informs the user the need to add invoices to the bill.

**Steps to Reproduce**
1. Load the cash payments page.
2. Select a cashbox with any currency defined.
3. Submit a payment without invoice items.

**Expected Result**
 The module should error with a nice error message ('You have not added invoices to pay against.  Please add them and resubmit')

**Actual Result**
 An HTTP POST is sent to `/cash` and returned as a 400 error without a good error message.

### PR DESCRIPTION
**Pull request by jniles**
This commit introduces a check to verify that invoices are being paid
against when a user submits the cash form.  If there are no invoices, a
danger notification is emitted telling the user to add some invoices and
no HTTP request is sent.

Previous, this would be validated on the server - the client no longer
even needs to make the HTTP request.

Closes #772.

----

Thank you for contributing!

Before submitting this pull request, please verify that you have:
 - [x] Run your code through JSHint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
 - [x] Run integration tests.
 - [x] Run end-to-end tests.
 - [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

File: client/src/partials/cash/cash.js [hunk 1]
```diff
@@ -149,17 +149,24 @@ function CashController(Cash, Cashboxes, AppCache, Currencies, Exchange, Session
...
+
+    // if the this is not a caution payment, but no invoices are selected,
+    // raise an error.
+    if (!isCaution && !hasInvoices) {
+      return Notify.danger('CASH.VOUCHER.NO_INVOICES_ASSIGNED');
+    }
 
     // submit the cash payment
-    if (hascaution) {
+    if (hasCaution) {
```
Comment (sfount) [inline client/src/partials/cash/cash.js:163]: :+1:

**Review by sfount — APPROVED** [review]
LGTM.
