### PR TITLE
Fixed expired stock report in refactor-stock-management branch

### LINKED ISSUE #5349: Align the columns of the Stock Expiration Report
The stock expiration report shows the stock that is expired or at risk of expiration, grouped by depot.  The columns do not line up between the different tables:
image

This is a bit annoying when trying to quickly scan the tables.  Let's make these columns line up.

### PR DESCRIPTION
**Pull request by jmcameron**
This PR fixes the Expired Stock Report.

The fix was to convert uses of lot.S_RISK (numerical flag) to lot.at_risk (boolean flag).   It seems to work with bhima_test, but I have not tested it with a production database.

Note the comment below for some questions about these variables (https://github.com/IMA-WorldHealth/bhima/pull/5438#issuecomment-786770857).

This PR was updated to address aligning columns between tables for each depot (see Issue https://github.com/IMA-WorldHealth/bhima/issues/5349)
Closes #5349

WARNING: This PR does not fix the totals for the stock at risk!  I'll add a note below about that (https://github.com/IMA-WorldHealth/bhima/pull/5438#issuecomment-786854885)

### CODE REVIEW

**Comment by jmcameron** [comment]
When I print out the lots in server/controllers/stock/reports/stock/expiration_report.js  (around line 48), I noticed some oddness with the data in each lot.  I've attached a sample of the output.

- It looks like the flags **expired, near_expiration, exhausted, at_risk**  appear both in the top level of the lot object as well as in the '**flags**' sub-object.   This duplication should probably be cleaned up.

- Using lot.S_RISK (numeric) as a flag should be avoided, now that we have lot.at_risk (boolean)?  We should probably check the usage of S_RISK everywhere.

- I see that the S_RISK, and S_RISK_QUANTITY have reasonable numeric values in some cases, and NaNs in others.  We should probably avoid  NaNs and set them to 'undefined' or 'null' when the calculation would produce NaNs.

[lots.txt](https://github.com/IMA-WorldHealth/bhima/files/6051235/lots.txt)

**Comment by jniles** [comment]
It might be too much to ask, but could you tackle https://github.com/IMA-WorldHealth/bhima/issues/5349 in this PR?

If you would prefer to keep this focused on the expired fix though, I understand.

**Comment by jmcameron** [comment]
> It might be too much to ask, but could you tackle #5349 in this PR?

Ok.  I'll see what I can do.

**Comment by jmcameron** [comment]
@jniles and @mbayopanda : Please do not release this PR before we fix the problem with the cost of at-risk stock not being handled.

@jniles:  Please look at server/controllers/stock/reports/stock/expiration_report.js around line 79+.
I tried changing lot.S_RISK_QUANTITY to lot.mvt_quantity (like the branch above).  It does produce results but I did not understand why they were marked as negatives and adding them to the value of expired stock did not make sense to me..  Please clarify how this should be handled!

**Review by mbayopanda — APPROVED** [review]
Thank @jmcameron for this PR as you said this work fixed column alignment.

The issue with totals of `at_risk` and if the `at_risk` status is correctly calculated must be addressed in another PR

**Comment by jmcameron** [comment]
> The issue with totals of `at_risk` and if the `at_risk` status is correctly calculated must be addressed in another PR

That sounds fine.  Do we have an issue for it or do we need to create one?

**Comment by jmcameron** [comment]
@jniles  I updated this (based on my best guess) to handle the value of the at-risk stock in the report.  Take a look at the code in server/controllers/stock/reports/stock/expiration_report.js around line 79+ see if that makes sense to you.  And try the report, obviously.  Your fixes in PR 5438 fixed the negatives issue.

File: server/controllers/stock/reports/stock/expiration_report.js [hunk 1]
```diff
@@ -47,10 +47,10 @@ async function stockExpirationReport(req, res, next) {
     const lots = await stockCore.getLotsDepot(options.depot_uuid, options);
 
     // get the lots that are "at risk"
-    const risky = lots.filter(lot => (lot.S_RISK < 0 && lot.lifetime > 0));
+    const risky = lots.filter(lot => (lot.at_risk && lot.lifetime > 0));
```
Comment (jniles) [inline server/controllers/stock/reports/stock/expiration_report.js]: So, I think this report is actually looking for "at risk of expiration".  This "at_risk" flag is "at_risk_of_stock_out".  The correct flag you are looking for is `lot.near_expiration` which will filter on lots that will expire before teh CMM says they will be consumed.  We could make that clearer.

File: server/controllers/stock/reports/stock/expiration_report.js [hunk 2]
```diff
@@ -76,12 +76,12 @@ async function stockExpirationReport(req, res, next) {
           totals.expired.quantity += lot.mvt_quantity;
           total += lot.value;
         } else {
-          lot.quantity_at_risk = (lot.S_RISK_QUANTITY * -1);
+          lot.quantity_at_risk = lot.mvt_quantity;
```
Comment (jniles) [inline server/controllers/stock/reports/stock/expiration_report.js]: The quantity at risk here should be the quantity that will expire at the current consumption rate.  The critical code is found here:

https://github.com/IMA-WorldHealth/bhima/blob/cdf85350d60f94f134f6e0ce7b0e0534ec88e8fb/server/controllers/stock/core.js#L787-L809

The value you are looking for is `S_RISK_QUANTITY`.  That should be the quantity of stock that will be lost at the current rate of consumption.  The amount of time that stock could have lasted, had it not expired, is in `S_RISK`.

File: server/controllers/stock/reports/stock/expiration_report.js (hunk 1 above)
Comment (jniles) [reply server/controllers/stock/reports/stock/expiration_report.js]: So, I think you can just change this to:
```js
 const risky = lots.filter(lot => lot.flags.near_expiration);
 ```

File: server/controllers/stock/reports/stock/expiration_report.js [hunk 3]
```diff
@@ -47,10 +47,10 @@ async function stockExpirationReport(req, res, next) {
     const lots = await stockCore.getLotsDepot(options.depot_uuid, options);
 
     // get the lots that are "at risk"
-    const risky = lots.filter(lot => (lot.S_RISK < 0 && lot.lifetime > 0));
+    const risky = lots.filter(lot => (lot.at_risk && lot.lifetime > 0));
 
     // get expired lots
-    const expired = lots.filter(lot => (lot.S_RISK <= 0 && lot.expiration_date <= today));
+    const expired = lots.filter(lot => (lot.expired && lot.expiration_date <= today));
```
Comment (jniles) [inline server/controllers/stock/reports/stock/expiration_report.js]: Similarly, this can be:
```js
const expired = lots.filter(lot => lot.flags.expired);
```

**Review by jniles — COMMENTED** [review]
@jmcameron the changes to the column sizes look good!  Much better alignment.

I believe that the `at_risk` here is being confused between "at risk of expiry" and "at risk of stock out".  I'll make an issue to propose renaming the `at_risk` flags to state specifically what they are.  I've made suggestions about how you can get the real values you are looking for.

File: server/controllers/stock/reports/stock_expiration_report.handlebars [hunk 4]
```diff
@@ -59,32 +59,32 @@
...
-            <td class="text-right">{{currency lot.value ../../metadata.enterprise.currency_id}}</td>
-            <td class="{{lot.classKey}}">{{translate lot.statusKey}}</td>
+            <td width="34%">{{lot.text}}</td>
+            <td width="12%">{{lot.label}}</td>
+            <td width="8%">{{date lot.expiration_date}}</td>
+            <td width="6%" class="text-right">{{lot.avg_consumption}}</td>
+            <td width="6%" class="text-right">{{lot.quantity}}</td>
+            <td width="6%" class="text-right">{{lot.quantity_at_risk}}</td>
+            <td width="6%">{{lot.unit_type}}</td>
+            <td width="5%">{{currency lot.unit_cost ../../metadata.enterprise.currency_id}}</td>
```
Comment (jniles) [inline server/controllers/stock/reports/stock_expiration_report.handlebars]: Can you make this cost `class="text-right"` as well?

**Review by jniles — COMMENTED** [review]
Just wanted to add one thing.  With these changes, here is what the Vanga report looks like:
image

File: server/controllers/stock/reports/stock_expiration_report.handlebars (hunk 4 above)
Comment (jmcameron) [reply server/controllers/stock/reports/stock_expiration_report.handlebars]: Done

File: server/controllers/stock/reports/stock/expiration_report.js (hunk 1 above)
Comment (jmcameron) [reply server/controllers/stock/reports/stock/expiration_report.js]: Done.

However, I'm still seeing duplication of the flags in the lot object as well as in log.flags.

File: server/controllers/stock/reports/stock/expiration_report.js (hunk 2 above)
Comment (jmcameron) [reply server/controllers/stock/reports/stock/expiration_report.js]: Done.

File: server/controllers/stock/reports/stock/expiration_report.js (hunk 3 above)
Comment (jmcameron) [reply server/controllers/stock/reports/stock/expiration_report.js]: Done

**Comment by jmcameron** [comment]
@jniles I did the updates you suggested and it seems to work correctly on bhima_test as well as IMCK (although I have not checked the numbers carefully there).  

Please take one last review.  If it is okay, let me know and I'll rebase it and release it.

**Comment by jmcameron** [comment]
I could also implement Issue https://github.com/IMA-WorldHealth/bhima/issues/5447 (renaming at_risk) before rebasing.

**Comment by jniles** [comment]
Let's hold off on the renaming one.  It will expand to multiple places.  I will give this a quick review this evening.

File: server/controllers/stock/reports/stock/expiration_report.js [hunk 5]
```diff
@@ -46,11 +46,11 @@ async function stockExpirationReport(req, res, next) {
     // get the lots for this depot
     const lots = await stockCore.getLotsDepot(options.depot_uuid, options);
 
-    // get the lots that are "at risk"
-    const risky = lots.filter(lot => (lot.S_RISK < 0 && lot.lifetime > 0));
+    // get the lots that are "at risk" of expiring
+    const risky = lots.filter(lot => (lot.near_expiration && lot.lifetime > 0));
```
Comment (jniles) [inline server/controllers/stock/reports/stock/expiration_report.js:50]: Nice 👍

File: server/controllers/stock/reports/stock/expiration_report.js [hunk 6]
```diff
@@ -46,11 +46,11 @@ async function stockExpirationReport(req, res, next) {
...
 
     // get expired lots
-    const expired = lots.filter(lot => (lot.S_RISK <= 0 && lot.expiration_date <= today));
+    const expired = lots.filter(lot => (lot.flags.expired && lot.expiration_date <= today));
```
Comment (jniles) [inline server/controllers/stock/reports/stock/expiration_report.js]: You probably don't need the expiration date check - the `expired` flag will already do that for you.

**Review by jniles — APPROVED** [review]
Approved.  Looks good to me.  I'll let you rebase and release at your leisure.

bors delegate+

File: server/controllers/stock/reports/stock/expiration_report.js (hunk 6 above)
Comment (jmcameron) [reply server/controllers/stock/reports/stock/expiration_report.js]: Fixed
