### PR TITLE
fix(cashboxes): load currency modal despite error

### LINKED ISSUE #3305: For a fresh installation, setting up accounts for each currencies throw an error
After a fresh installation of bhima with as main currency 'CDF', when we create a cashbox it is not possible to setting up the account for each currencies.

image

### PR DESCRIPTION
**Pull request by jniles**
Do not crash when an error occurs looking up the cashbox currency.  On the create state, the `resolve` would error, causing the `$state` change to abort and never show the modal.  This logic has been moved into the modal now and the error handled in that context.

Closes #3305.

### CODE REVIEW

File: client/src/modules/cash/cashboxes/configure_currency/modal.js [hunk 1]
```diff
@@ -2,34 +2,44 @@ angular.module('bhima.controllers')
...
-  vm.data = data;
-  vm.data.currency_id = currency.id;
+
+  Cashboxes.currencies.read(cashbox.id, currency.id)
+    .then(data => {
+      vm.data = data;
+      vm.data.currency_id = currency.id;
+    })
+    // if no accounts found, no problem!  We are in the "create" state then.
+    .catch(angular.noop);
```
Comment (mbayopanda) [inline client/src/modules/cash/cashboxes/configure_currency/modal.js:41]: 🤐

File: client/src/modules/cash/cashboxes/update/update.js [hunk 2]
```diff
@@ -12,7 +12,7 @@ function CashboxUpdateController($state, Modal, ModalService, Notify, Boxes, Cur
   const CREATE_STATE = 'cashboxes.create';
 
   // temporary method of determining if we're in create state
-  const creating = $state.current.name === CREATE_STATE;
+  const isCreateState = $state.current.name === CREATE_STATE;
```
Comment (mbayopanda) [inline client/src/modules/cash/cashboxes/update/update.js:15]: 👍 good name

**Review by mbayopanda — APPROVED** [review]
LGTM 👍 

bors r+

**Comment by jniles** [comment]
bors r+

_one last try_
