### PR TITLE
fix(cashbox): ensure is_auxiliary is updated

### LINKED ISSUE #976: (bug) Cashboxes page does not always load is_auxiliary properly
In production, we are seeing the cashboxes radio select not always properly configured with "primary" or "auxiliary" cashboxes.  The database has a definition for this table, the radio buttons do not show it on the edit cashbox page.

### PR DESCRIPTION
**Pull request by jniles**
This commit should fix the issues in cashbox management where cashboxes
were not properly updated with the is_auxiliary field.  It also
generally improves the code by:
 1. Using the translate directive on the client.
 2. Using `db.one()` on the server.
 3. Using `FilterParser` on the server.

Closes #976.

----
Thank you for contributing!

Before submitting this pull request, please verify that you have:
 - [x] Run your code through JSHint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
 - [x] Run integration tests.
 - [x] Run end-to-end tests.
 - [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

File: server/controllers/finance/cashboxes/index.js [hunk 1]
```diff
@@ -33,56 +35,33 @@ exports.currencies = currencies;
...
- *  1) ?project_id={id}
- *  2) ?is_auxiliary={1|0}
- *  3) ?detailed={1|0}
- * to filter results appropriately.
  */
 function list(req, res, next) {
-  const possibleConditions = ['project_id', 'is_auxiliary'];
-  const providedConditions = Object.keys(req.query);
-  const conditions = [];
+  const filters = new FilterParser(req.query);
```
Comment (sfount) [inline server/controllers/finance/cashboxes/index.js:40]: :+1:

**Review by sfount — APPROVED** [review]
LGTM. Great use of the latest standards.
