### PR TITLE
fix(migrate): read from .env.production

### LINKED ISSUE #4665: Default to reading `.env.production` in setup-migration-script.sh
In our [migration script](https://github.com/IMA-WorldHealth/bhima/blob/master/sh/setup-migration-script.sh) we read `.env.development`.  This is almost never what I want when I am migrating a database - I always want to migrate the database in `.env.production` since that is where I do my testing.

We should probably just make it default to `.env.production` unless someone passes another variable in.

### PR DESCRIPTION
**Pull request by jniles**
Defaults to reading from `.env.production` from the migration setup script.

Closes #4665.

### CODE REVIEW

File: sh/setup-migration-script.sh [hunk 1]
```diff
@@ -14,8 +14,12 @@ set -uo pipefail
 
 echo "[migrate] Migrating BHIMA database"
 
+ENVIRONMENT=${ENVIRONMENT:-"production"}
+
+echo "[migrate] Reading from $ENVIRONMENT."
+
 set -a
-source .env.development
+source .env.$ENVIRONMENT
```
Comment (mbayopanda) [inline sh/setup-migration-script.sh:22]: I would like to know where to set the `ENVIRONMENT` if we want to run in production or in development mode

Comment (jniles) [reply sh/setup-migration-script.sh:22]: On line 17, it is set to "production" by default.  However you can change this the same way you set any environmental variable in bash, by just passing it in.  Like this:
```sh
ENVIRONMENT="development" yarn migrate
# now ENVIRONMENT will be "development"
```
or 
```sh
exports ENVIRONMENT="development"
yarn migrate
```
etc.

**Comment by jmcameron** [comment]
Does this impact the installation directions?

**Comment by jniles** [comment]
No, not the installation directions, but it does have some impact on the [upgrading documentation](https://docs.bhi.ma/en/for-developers/upgrading-bhima.html).  We should probably mention that you can change the default environment.

In the long run, we really should be doing https://github.com/IMA-WorldHealth/bhima/issues/3146 though.
