### PR TITLE
fix(Trial Balance): limit lookup to FY

### LINKED ISSUE #2568: Trial Balance does not limit to most recent fiscal year
The Trial Balance groups the entire period totals table when calculating the `balance_before` column in the Trial Balance view.  While is acceptable if all data is correct, if previous fiscal years have corrupted data, it perpetuates the data corruption.

This causes the `balance_before` to be different from the balance reported by both the General Ledger and the Account Statement.  We should bring the Trial Balance in line with those two reports.

### PR DESCRIPTION
**Pull request by jniles**
This commit limits the Trial Balance lookup to only oldest fiscal year.

Closes #2568.

### CODE REVIEW

File: server/models/procedures/trial_balance.sql [hunk 1]
```diff
@@ -190,23 +190,36 @@ CREATE PROCEDURE TrialBalanceSummary()
...
+      WHERE period_total.fiscal_year_id = fiscalYearId
+    ) totals ON u.account_id = totals.account_id
     GROUP BY u.account_id;
 
   SELECT account_id, account.number AS number, account.label AS label,
     balance_before, debit_equiv, credit_equiv,
     balance_before + debit_equiv - credit_equiv AS balance_final
   FROM (
-    SELECT posting_journal.account_id, SUM(totals.balance_before) AS balance_before, SUM(debit_equiv) AS debit_equiv,
+    SELECT posting_journal.account_id, MAX(totals.balance_before) AS balance_before, SUM(debit_equiv) AS debit_equiv,
```
Comment (mbayopanda) [inline server/models/procedures/trial_balance.sql:222]: Could you fix this `MAX` if it is required, in my test i cannot see the error with `MAX`

**Review by mbayopanda — COMMENTED** [review]
I did a test locally with the test dataset the trial balance shows correct values. 

it looks good to me 👍
