### PR TITLE
chore(lint): fix server lint issues

### LINKED ISSUE #1429: (refactor) Eliminate lint errors on the server
The server is currently full of lint errors after the transition to eslint.  I propose that we target the server for cleanup.  The benefits will be:
 1. More syntactically similar code throughout the application
 2. An opportunity to remove and deprecate old code/libraries that are unused
 3. An opportunity to catch any bugs caught by a stricter linter
 4. The ability to lint as a test on Travis CI or other integration test suites.

The current state is:
```sh
✖ 3532 problems (1725 errors, 1807 warnings)
```

### PR DESCRIPTION
**Pull request by jniles**
This commit makes the server pass ESLint. For the most part, all of the
logic remains unchanged; however, the following files have been
completely removed until they can be designed:
 1. `PluginManager` - a hold-out from 1.x.
 2. `errors/index.js` - never actually used on the server.
 3. `finance/ledger.js` - never actually used.

In a few places, ES Lint rules have been added to the top of files to
prevent errors from being thrown for that file.  Ideally, this should be
on a line level.

Closes #1429.

-----

Thank you for contributing!

Before submitting this pull request, please verify that you have:
 - [x] Run your code through ESLint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
 - [x] Run integration tests.
 - [x] Run end-to-end tests.
 - [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

File: server/controllers/finance/reports/balance/index.js [hunk 1]
```diff
@@ -105,37 +102,39 @@ function processAccounts(balances, accounts, totals) {
...
-    return totals;
-  }, {
-    beginDebit   : 0,
-    beginCredit  : 0,
-    middleDebit  : 0,
-    middleCredit : 0,
-    endDebit     : 0,
-    endCredit    : 0,
-  });
+  const vtotals = Object.keys(accounts)
```
Comment (sfount) [inline server/controllers/finance/reports/balance/index.js:118]: I thought that this report/ code had been replaced with MySQL maths logic? This code should be removed as soon as possible.

**Review by sfount — APPROVED** [review]
Very welcome improvements to the linting process!
