### PR TITLE
Bug cash flow report

### LINKED ISSUE #3454: (bug) Cash Flow Report
The cash flow report
- should not show deleted transactions
- The balance of the cashboxes of each period should be equal with the reports of accounts
- The Cash Flow Report should not show the expenses in absolute terms

### PR DESCRIPTION
**Pull request by lomamech**
- Fix and Refactor Sql Request for Cash flow Report By Cashbox
- Refactor Report, remove Others Sections
- Display Expenses in Absolute value

closes #3454

### CODE REVIEW

**Comment by lomamech** [comment]
@jniles need review

File: server/controllers/finance/reports/cashflow/index.js [hunk 1]
```diff
@@ -280,54 +271,79 @@ function report(req, res, next) {
...
+        data.dateFrom,
+        data.dateTo];
+      return db.exec(query, params);
     })
     .then(rows => {
       // split incomes from expenses
       const incomes = _.chain(rows).filter({ transaction_type : 'income' }).groupBy('transaction_text').value();
       const expenses = _.chain(rows).filter({ transaction_type : 'expense' }).groupBy('transaction_text').value();
-      const transfers = _.chain(rows).filter({ transaction_type : 'transfer' }).groupBy('transaction_text').value();
+      const others = _.chain(rows).filter({ transaction_type : 'other' }).groupBy('transaction_text').value();
```
Comment (jniles) [inline server/controllers/finance/reports/cashflow/index.js:318]: Good catch.  I wish we could write this in SQL.

File: server/models/bhima.sql [hunk 2]
```diff
@@ -199,6 +199,12 @@ INSERT INTO `transaction_type` (`id`, `text`, `type`, `fixed`) VALUES
   (18, 'VOUCHERS.SIMPLE.ADJUSTMENT', 'other', 1),
   (19, 'VOUCHERS.SIMPLE.CAUTION_LINK', 'other', 1);
 
+INSERT INTO `transaction_type` (`text`, `type`, `fixed`) VALUES
```
Comment (jniles) [inline server/models/bhima.sql:202]: We'll need to put this into our migrate.sql script

File: server/controllers/finance/reports/cashflow/report.handlebars [hunk 3]
```diff
@@ -132,12 +100,15 @@
...
+              <td colspan="{{colspan}}">&nbsp;</td>
+            </tr>            
           </tbody>
 
           <tbody>
-            {{!-- TOTALS --}}
+            {{!-- BALANCE --}}
             <tr style="background-color: #efefef;font-size:1.3rem;">
-              <th class="text-left text-uppercase">{{translate 'FORM.LABELS.TOTAL'}}</th>
+              <th class="text-left text-uppercase">{{translate 'FORM.LABELS.BALANCE'}}</th>
```
Comment (jniles) [inline server/controllers/finance/reports/cashflow/report.handlebars:111]: 👍

File: server/controllers/finance/reports/cashflow/index.js [hunk 4]
```diff
@@ -280,54 +271,79 @@ function report(req, res, next) {
...
+          JOIN account AS a ON a.id = gl.account_id
+          JOIN transaction_type AS tt ON tt.id = gl.transaction_type_id
+          WHERE gl.account_id IN ? AND ((DATE(gl.trans_date) >= DATE(?)) AND (DATE(gl.trans_date) <= DATE(?)))
+          AND gl.transaction_type_id <> 10 AND gl.trans_id NOT IN (
+            SELECT DISTINCT gl.trans_id
+            FROM general_ledger AS gl
+            WHERE gl.record_uuid IN (
+              SELECT rev.uuid
+              FROM (
+                SELECT v.uuid, v.date, v.reversed
```
Comment (jniles) [inline server/controllers/finance/reports/cashflow/index.js]: I know it is more code to write, but this should be faster if you do the WHERE condition in each table individually.  This is because `UNION` will group everything, then remove duplicates.  A faster way would be :
```sql
SELECT v.uuid FROM voucher v WHERE v.reversed = 1 AND DATE(v.date) >= DATE(?) AND DATE(v.date) <= DATE(?) UNION
SELECT c.uuid FROM cash c WHERE c.reversed = 1 AND DATE(c.date) >= DATE(?) AND DATE(c.date) <= DATE(?) UNION
SELECT i.uuid FROM invoice i WHERE i.reversed = 1 AND DATE(i.date) >= DATE(?) AND DATE(i.date) <= DATE(?)
```

File: server/controllers/finance/reports/cashflow/index.js [hunk 5]
```diff
@@ -280,54 +271,79 @@ function report(req, res, next) {
...
-          FROM general_ledger gl
-          JOIN account a ON gl.account_id = a.id
-          JOIN transaction_type tt ON gl.transaction_type_id = tt.id
-          WHERE gl.uuid IN ?
-          GROUP BY a.id, tt.id
+          SELECT 
+          a.number AS account_number, a.label AS account_label,
+          IF (tt.text = 'expense', SUM(gl.credit_equiv - gl.debit_equiv),
+          SUM(gl.debit_equiv - gl.credit_equiv)) AS balance,
+          gl.transaction_type_id AS transaction_id, tt.type AS transaction_type, tt.text AS transaction_text,
```
Comment (jniles) [inline server/controllers/finance/reports/cashflow/index.js]: And we not re-name `transaction_type_id` to `transaction_id`?  It is not a `transaction_id`.  It's a `transaction_type_id`.

File: server/controllers/finance/reports/cashflow/report.handlebars [hunk 6]
```diff
@@ -62,14 +62,17 @@
...
+            </tr>
           </tbody>
 
           <tbody>
             {{!-- EXPENSES --}}
             <tr style="background-color: #efefef;font-size:1.3rem;">
               <th class="text-left text-uppercase">{{translate 'REPORT.CASHFLOW.EXPENSES'}}</th>
               {{#each periods as |period| }}
-                <th class="text-right">{{debcred (look ../expenseTotal period) ../metadata.enterprise.currency_id}}</th>
+                <th class="text-right">{{debcred (multiply (look ../expenseTotal period) -1) ../metadata.enterprise.currency_id}}</th>
```
Comment (jniles) [inline server/controllers/finance/reports/cashflow/report.handlebars:75]: Why are we multiplying this by negative one?

File: server/controllers/finance/reports/cashflow/index.js [hunk 7]
```diff
@@ -280,54 +271,79 @@ function report(req, res, next) {
...
+          a.number AS account_number, a.label AS account_label,
+          IF (tt.text = 'expense', SUM(gl.credit_equiv - gl.debit_equiv),
+          SUM(gl.debit_equiv - gl.credit_equiv)) AS balance,
+          gl.transaction_type_id AS transaction_id, tt.type AS transaction_type, tt.text AS transaction_text, 
+          gl.account_id, gl.period_id
+          FROM general_ledger AS gl
+          JOIN account AS a ON a.id = gl.account_id
+          JOIN transaction_type AS tt ON tt.id = gl.transaction_type_id
+          WHERE gl.account_id IN ? AND ((DATE(gl.trans_date) >= DATE(?)) AND (DATE(gl.trans_date) <= DATE(?)))
+          AND gl.transaction_type_id <> 10 AND gl.trans_id NOT IN (
```
Comment (jniles) [inline server/controllers/finance/reports/cashflow/index.js]: Hmm... In 2.x, `gl.record_uuid` should map one to one with `gl.trans_id`.  I know this isn't the case in IMCK's database, unfortunately.

What happens if you do:
```sql
AND gl.transaction_type_id <> 10
AND gl.record_uuid NOT IN (SELECT rev.uuid /* ... etc */);
```

Since `trans_id` is a string and `record_uuid` is binary, it is much, much faster to use `record_uuid` than `trans_id`.

**Review by jniles — COMMENTED** [review]
@lomamech, I've made a few comments.  Great work trying to sort this out - I know it could not have been easy.

File: server/controllers/finance/reports/cashflow/report.handlebars (hunk 6 above)
Comment (lomamech) [reply server/controllers/finance/reports/cashflow/report.handlebars:75]: For a fund to spend money the account is credited, and to know the balance of this account it is done by debit - credit, so that the balance will be negative, and for posting the report Cashflow values must be positive, which is why I have multiplied the values of transactions with the standard transaction affected by expence by (-1)

File: server/controllers/finance/reports/cashflow/index.js (hunk 7 above)
Comment (lomamech) [reply server/controllers/finance/reports/cashflow/index.js]: I will do it

File: server/models/migrations/v0.8.0-v0.9.0/migrate.sql [hunk 8]
```diff
@@ -964,3 +964,12 @@ WHERE id = 199;
 UPDATE role_unit SET unit_id = 199 WHERE unit_id = 159;
 DELETE FROM unit WHERE id = 159;
 DELETE FROM report WHERE id = 9;
+
+-- author : @lomamech
+-- Add new transaction type
+-- 2018-12-10
+INSERT INTO `transaction_type` (`text`, `type`, `fixed`) VALUES
```
Comment (jniles) [inline server/models/migrations/v0.8.0-v0.9.0/migrate.sql:973]: Nice :+1:

**Review by jniles — APPROVED** [review]
All comments have been addressed.  Well done!

bors r+

**Review by jniles — APPROVED** [review]
All comments have been addressed.  Well done!

bors r+

**Comment by lomamech** [comment]
@jniles  Patrick asked me to add two more standard transaction to identify the transactions between the Main Fund and the bank

**Comment by jniles** [comment]
Tests pass!

bors r+
