### PR TITLE
Automatically update stock lot expiration dates in bhima_test

### LINKED ISSUE #4796: Fix bhima_test database installation to update stock expiration dates
The current Bhima_test database has stock lots with specific fixed expiration dates that are mostly in the past.
We should add SQL code to test/data.sql to update any items with fixed dates to have dates close to the present.  For instance:

 * stock lots expiration date - Update most of the items to expire in the future, but leave some in the past for testing purposes
 * fiscal years - Add the current year
 * offdays - Add offdays for the current year

The data in test/data.sql should be examined to see if other items need to be updated as well.

Note that these changes will probably affect the regression tests.  So whoever fixes this issue will need to fix the broken tests as well.

### PR DESCRIPTION
**Pull request by jmcameron**
This update updates the stock lots as follows:
- Most stock lots expire 2 years from the date the database is loaded (by: yarn build:db)
- Quinine lot QUININE-A expired: 2017-04-30
- Quinine lot QUININE-B expires 1 month in the future

Based on the changes made to the lot expiration dates, all but one of the lots should not be expired no matter when bhima_test tests are run.

Suggestions for Testing:
- Run 'yarn build:db' with the updates in the pull request
- Run bhima (yarn dev)
- In the browser, go to Stock > Stock Lots, you should see 5 items.  Only one will be expired (in red).
- When you change the search filter to select expired/unexpired, you should see appropriate list changes
- When you implement a search filter date range of 1/1/2017 thru 31/12/2017, you should see only the one expired item (in red).

Several of the end-to-end and integration tests needed to be updated, as expected.   Updates were made, but in some cases it was not clear why the necessary changes were needed.    However, when I ran the BHIMA interactively (yarn dev), the behavior in the  stock lot registry and associated filtering worked as expected.

### CODE REVIEW

File: test/data.sql [hunk 1]
```diff
@@ -2987,11 +2987,11 @@ SET @multivitamine = HUID('f6556e72-9d05-4799-8cbd-0a03b1810185');
...
-  (HUID('064ab1d9-5246-4402-ae8a-958fcdb07b35'), 'VITAMINE-A', 100, 100, 1.2000, '2019-04-30', @multivitamine, HUID('e07ceadc-82cf-4ae2-958a-6f6a78c87588'), 0, '2017-02-02 11:09:25'),
-  (HUID('5a0e06c2-6ca7-4633-8b17-92e2a59db44c'), 'VITAMINE-B', 20, 20, 0.5000, '2020-04-30', @multivitamine, HUID('e07ceadc-82cf-4ae2-958a-6f6a78c87588'), 0, '2017-02-02 11:09:25'),
-  (HUID('6f80748b-1d94-4247-804e-d4be99e827d2'), 'QUININE-B', 200, 200, 0.8000, '2018-04-30', @quinine, HUID('e07ceadc-82cf-4ae2-958a-6f6a78c87588'), 0, '2017-02-02 11:09:25'),
-  (HUID('ae735e99-8faf-417b-aa63-9b404fca99ac'), 'QUININE-A', 100, 100, 1.2000, '2018-04-30', @quinine, HUID('e07ceadc-82cf-4ae2-958a-6f6a78c87588'), 0, '2017-02-02 11:09:25'),
-  (HUID('ef24cf1a-d5b9-4846-b70c-520e601c1ea6'), 'QUININE-C', 50, 50, 2.0000, '2017-04-30',   @quinine, HUID('e07ceadc-82cf-4ae2-958a-6f6a78c87588'), 0, '2017-02-02 11:09:25');
+  (HUID('064ab1d9-5246-4402-ae8a-958fcdb07b35'), 'VITAMINE-A', 100, 100, 1.2000, date_add(CURRENT_DATE, INTERVAL 2 YEAR), @multivitamine, HUID('e07ceadc-82cf-4ae2-958a-6f6a78c87588'), 0, '2017-02-02 11:09:25'),
```
Comment (jniles) [inline test/data.sql:2990]: Very nice 👍

File: test/end-to-end/stock/stock.lots.spec.js [hunk 2]
```diff
@@ -82,7 +82,7 @@ function StockLotsRegistryTests() {
   it('find lots by expiration date', async () => {
     await modal.setdateInterval('01/01/2017', '31/12/2017', 'expiration-date');
     await modal.submit();
-    await GU.expectRowCount(gridId, 1 + depotGroupingRow);
+    await GU.expectRowCount(gridId, depotGroupingRow - 1); // 1 expired in this date range
```
Comment (jniles) [inline test/end-to-end/stock/stock.lots.spec.js:85]: I'm quite surprised this is the only test that needs to change.  But this is great!

**Review by jniles — APPROVED** [review]
This makes me feel so much better!  I've tested it and it looks fine to me.  Thanks so much @jmcameron! 

bors r+

File: test/end-to-end/stock/stock.lots.spec.js (hunk 2 above)
Comment (jmcameron) [reply test/end-to-end/stock/stock.lots.spec.js:85]: Actually I ended up changing 3-4 tests.  Not sure why this is the only one that showed up.
