### PR TITLE
fix(vouchers): sync voucher currency w/ footer

### LINKED ISSUE #1286: (bug) Complex Vouchers do not update with the correct currency in the footer
The Complex Voucher grid caches the currency in the footer and does not update it when the user changes currency.  The solution is to use a `footerCellFilter`.  See below:

journalvoucherstotalscurrencyincorrect
_Fig 1 : Journal Vouchers Currency Rendering Broken_

### PR DESCRIPTION
**Pull request by jniles**
This commit fixes the voucher footer aggregation, keeping it in sync
with the form's selected currency.  It also switches complex.html to
using the `translate` directive.

Closes #1286.

----
Thank you for contributing!

Before submitting this pull request, please verify that you have:
 - [x] Run your code through ESLint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
 - [x] Run integration tests.
 - [x] Run end-to-end tests.
 - [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

File: client/src/partials/vouchers/complex.js [hunk 1]
```diff
@@ -163,51 +163,52 @@ function ComplexJournalVoucherController(Vouchers, $translate, Currencies, Sessi
...
-    aggregationType: uiGridConstants.aggregationTypes.sum,
+    field                : 'credit',
+    displayName          : 'FORM.LABELS.CREDIT',
+    headerCellFilter     : 'translate',
+    cellTemplate         : 'partials/vouchers/templates/credit.grid.tmpl.html',
+    aggregationType      : uiGridConstants.aggregationTypes.sum,
     aggregationHideLabel : true,
-    footerCellFilter: 'currency:' + Session.enterprise.currency_id,
-    footerCellClass : 'text-right'
+    footerCellFilter     : 'currency:grid.appScope.Voucher.details.currency_id',
```
Comment (sfount) [inline client/src/partials/vouchers/complex.js:195]: :+1:

**Review by sfount — APPROVED** [review]
LGTM.
