### PR TITLE
Fix: limit csv renderer output with filters

### LINKED ISSUE #1123: (refactor) Remove "Download as JSON" from bhRendererDropdown
The "Download as JSON" option is not very useful from the `bhRenderDropdown` - it was largely just a proof of concept.  It should be removed in production.

### PR DESCRIPTION
**Pull request by jniles**
This PR fixes two issues:
 1. It removes the JSON option from the `bhRendererDropdown` component.  Closes #1123. 
 2. It preserves the filters to send back to the server.  Closes Vanga-Hospital#221.

Parameters are watched for changes on the component border and are subsequently serialized and passed to the `ngHref`.

---
Thank you for contributing!

Before submitting this pull request, please verify that you have:
 - [x] Run your code through JSHint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
 - [x] Run integration tests.
 - [x] Run end-to-end tests.
 - [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

File: client/src/js/components/bhRendererDropdown.js [hunk 1]
```diff
@@ -8,35 +8,63 @@ angular.module('bhima.components')
...
 
-function bhRendererController(AppCache) {
+function bhRendererController(AppCache, $httpParamSerializer) {
   var $ctrl = this;
 
   var cache = new AppCache('bhRendererComponent');
 
   // delay between GET request completion and loading indication, this is used
   // to compensate for the delay in browsers opening the print dialog
+  // @todo - make this work!
```
Comment (sfount) [inline client/src/js/components/bhRendererDropdown.js:20]: 😆 Was this supposed to be left in?

File: client/src/js/components/bhRendererDropdown.js [hunk 2]
```diff
@@ -8,35 +8,63 @@ angular.module('bhima.components')
     controller : bhRendererController
   });
 
-bhRendererController.$inject = [ 'appcache' ];
+bhRendererController.$inject = [ 'appcache', '$httpParamSerializer' ];
```
Comment (sfount) [inline client/src/js/components/bhRendererDropdown.js:11]: 👍. I didn't know about this library.

**Review by sfount — APPROVED** [review]
LGTM.

File: client/src/js/components/bhRendererDropdown.js (hunk 2 above)
Comment (jniles) [reply client/src/js/components/bhRendererDropdown.js:11]: Yeah, `$http` uses it internally :)

File: client/src/js/components/bhRendererDropdown.js (hunk 1 above)
Comment (jniles) [reply client/src/js/components/bhRendererDropdown.js:20]: Yeah ... it currently doesn't actually have any loading indicator.  I'm actually not sure how to get the loading status of a `a[download]` tag.  Do you know how to?
