### PR TITLE
fix(reports): allow saving Items in Stock

### LINKED ISSUE #4109: "Articles in Stock" does not save as PDF
The Articles In Stock Report does not save as PDF properly.  Here is what it looks like:

8xlqVKLH5o

I'm sure I broke it when I changed the way the URL parameters were passed to the server.

### PR DESCRIPTION
**Pull request by jniles**
Fixes saving the "items in stock" report that was accidentally applying a filter based on the filename.

Closes #4109.

### CODE REVIEW

File: server/controllers/stock/reports/stock/inventories_report.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 const {
-  _, ReportManager, Stock, formatFilters, pdfOptions, STOCK_INVENTORIES_REPORT_TEMPLATE,
```
Comment (mbayopanda) [inline server/controllers/stock/reports/stock/inventories_report.js:2]: 👍

File: server/controllers/stock/reports/stock/inventories_report.js [hunk 2]
```diff
@@ -34,6 +35,8 @@ async function stockInventoriesReport(req, res, next) {
       options = req.query;
     }
 
+    delete options.label;
```
Comment (mbayopanda) [inline server/controllers/stock/reports/stock/inventories_report.js:38]: 👍

**Review by mbayopanda — APPROVED** [review]
bors r+
