### PR TITLE
fix: stock depot selection issues

### LINKED ISSUE #1986: bug: bhDepotSelect shows "no depot" message on slow network
The bhDepotSelect component shows "No Depots" error message when the network is slow.  This can be very confusing since there are depots available, but they are simply not loaded.  It should show a loading indicator instead.

bugnodepotwhendepotactuallyexists
_Fig 1: Misleading Error when Depots Actually are Loading_

### LINKED ISSUE #2003: (proposal) make the stock modules depot selection the same as cash window
The cash window proposed a method for selecting a 'Cash Box' using a modal selection and including the name of the cash box in bold in the headercrumb ™️ . 

I propose that we use this same UX pattern for the stock modules. Anything to help users know exactly which depot they are currently in will be a benefit. It will also make all of BHIMA feel like the same product. 

I do not think this has to be state based like the cash window - I think the cash window should no longer be state based.

### LINKED ISSUE #2094: bug: depot select tests fail intermittently
We have a flaky test on Travis CI and locally - [Stock Entry from depot Secondaire](https://travis-ci.org/IMA-WorldHealth/bhima-2.X/jobs/274655042#L1913).  This is causing many false signals in our PRs.  We also know that this [depot selection component is buggy](https://github.com/IMA-WorldHealth/bhima-2.X/issues/1986).  There is a proposal (https://github.com/IMA-WorldHealth/bhima-2.X/issues/2003) to improve it.  Since it's causing so much havoc with our PRs, I think re-writing this component should be high priority.

### PR DESCRIPTION
**Pull request by jniles**
This PR addresses multiple issues associated with depot selection in the stock management modules.  It implements the suggestion in #2003 and removes the `bhDepotDropdown`.

The basic idea is to make depot selection like cashbox selection, where a user is presented a modal if they have no depot selected. This modal is shown below:
depotselectionfirsttime
_Fig 1: Depot Selection if no depot is selected_

Depots are cached between selections, so a page will always use the selected depot.  They are not (yet) cached between pages ... although this would be as simple as changing the cache key.

Changing the depot is accessible via the dropdown menu as on most pages:
depotselectionmenu
_Fig 2: Depot Selection Menu_

Any subsequent selections bring up the following modal:
depotselectionallothertimes
_Fig 3: Depot Selection Modal All Other Times_

Closes #2003.  Closes #2094.  Closes #1986.

### CODE REVIEW

**Comment by jniles** [comment]
@dedrickenc, tests pass.

**Comment by DedrickEnc** [comment]
I will have a look tomorrow morning

**Comment by jniles** [comment]
Sounds good!

File: client/src/js/services/StockService.js [hunk 1]
```diff
@@ -45,40 +45,39 @@ function StockService(Api, Filters, AppCache, Periods, $httpParamSerializer, Lan
...
+  if (filterMovementCache.filters) {
     StockMovementFilters.loadCache(filterMovementCache.filters);
   }
 
   // once the cache has been loaded - ensure that default filters are provided appropriate values
   assignLotDefaultFilters();
   assignMovementDefaultFilters();
 
-  // creating an an object of filter to avoid method duplication
+  // creating an object of filter to avoid method duplication
```
Comment (DedrickEnc) [inline client/src/js/services/StockService.js:70]: good catch

File: client/src/modules/cash/cash.html [hunk 2]
```diff
@@ -11,7 +11,7 @@
       <div class="toolbar-item">
         <div uib-dropdown dropdown-append-to-body data-action="open-tools">
           <a class="btn btn-default" uib-dropdown-toggle>
-            <span translate>FORM.LABELS.MENU</span> <span class="caret"></span>
+            <span class="fa fa-bars"></span> <span class="hidden-xs" translate>FORM.LABELS.MENU</span> <span class="caret"></span>
```
Comment (DedrickEnc) [inline client/src/modules/cash/cash.html:14]: A good enhancement

File: client/src/modules/depots/depots.service.js [hunk 3]
```diff
@@ -10,7 +10,28 @@ DepotService.$inject = ['PrototypeApiService'];
...
+function DepotService(Api, Modal) {
   var service = new Api('/depots/');
+
+  /**
+   * @method openSelectionModal
+   *
+   * @description
+   * Opens the selection modal to allow a user to select a depot.
+   *
+   * @returns Promise - a promise containing the depot.
```
Comment (DedrickEnc) [inline client/src/modules/depots/depots.service.js]: or a promise containing a selected depot

File: client/src/i18n/en/depot.json [hunk 4]
```diff
@@ -1,22 +1,30 @@
...
+    "DEPOTS_LIST" : "Depots list",
+    "DESCRIPTION" : "This module allows you to List, Create, Edit and Delete a Depot",
+    "EDIT_DEPOT" : "Edit the information in a Depot",
+    "ENTITY" : "Depot",
+    "LABEL" : "Depot",
+    "MAIN" : {
+      "TITLE" : "Depot Management"
+    },
+    "NO_DEPOT" : "No Depot",
+    "NOT_ALLOWED_ACTIONS" : "This depot is protect.  You cannot modify its properties.",
```
Comment (jniles) [inline client/src/i18n/en/depot.json]: Whoops, this should say "this depot is protected." instead of "this depot is protect."

File: client/src/i18n/en/depot.json [hunk 5]
```diff
@@ -1,22 +1,30 @@
...
+    "TITLE" : "Depot Management",
+    "UPDATED" : "Depot updated with success",
+    "WAREHOUSE" : "Warehouse",
+    "MODAL" : {
+      "SELECTION" : "Depot Selection",
+      "NO_DEPOTS" : "Do not see any depots?",
+      "SELECT_A_DEPOT" : "Select a depot",
+      "NO_DEFAULT_DEPOT" : "Oops!  We need you to choose a depot.",
```
Comment (jniles) [inline client/src/i18n/en/depot.json]: This would be better said ad "You need to choose a depot."

File: client/src/modules/stock/adjustment/adjustment.js [hunk 6]
```diff
@@ -127,12 +122,32 @@ function StockAdjustmentController(Depots, Inventory, Notify,
...
+      date : new Date(),
+      entity : {},
+    };
+
+    vm.depot = cache.depot;
+
+    // make sure that the depot is loaded if it doesn't exist at startup.
+    if (vm.depot) {
+      setupStock();
+      loadInventories(vm.depot);
```
Comment (jniles) [inline client/src/modules/stock/adjustment/adjustment.js]: Technically, this repeated code could be combined into a single function:
```js
function setupStock(depot) {
  // old code
  loadInventories(vm.depot);
  checkValidity();
}

// later..

if (vm.depot) {
  setupStock(vm.depot);
} else {
  changeDepot()
    .then(setupStock);
}
```

Slight code reduction here by about two lines.

File: client/src/modules/stock/depot-selection.modal.html [hunk 7]
```diff
@@ -0,0 +1,72 @@
...
+      <i class="fa fa-link"></i> <span translate>DEPOT.ADD_DEPOT</span>
+    </a>
+  </p>
+
+  <div uib-alert class="alert-warning" ng-if="$ctrl.hasNoDefaultDepot">
+    <p>
+      <strong> <i class="fa fa-warning"></i> <span translate>DEPOT.MODAL.NO_DEFAULT_DEPOT</span></strong>
+      <br />
+      <span translate>DEPOT.MODAL.SELECTION_EXPLANATION</span>
+      <a href ui-sref="depots.create"><b><span translate>DEPOT.ADD_DEPOT</span></b></a>.
```
Comment (jniles) [inline client/src/modules/stock/depot-selection.modal.html]: It would be nice if this was a colored yellow like the rest of the alert.  It is currently blue, which really stands out and clashes with the rest of the colors.

File: client/src/modules/stock/entry/entry.html [hunk 8]
```diff
@@ -95,8 +115,8 @@
     </div>
 
     <!-- grid -->
-    <div id="stock-entry-grid" 
-      ui-grid="StockCtrl.gridOptions" 
+    <div id="stock-entry-grid"
+      ui-grid="StockCtrl.gridOptions"
       style="height: 300px; width: 100%;"
```
Comment (jniles) [inline client/src/modules/stock/entry/entry.html:120]: It would be nice if these styles were contained in the `bhima-bootstrap.less` file.  This should probably be a separate PR that addresses it here and in all other modules that have this style of `ui-grid`.

File: test/end-to-end/stock/stock.lots.spec.js [hunk 9]
```diff
@@ -51,6 +51,7 @@ function StockLotsRegistryTests() {
   });
 
   it('find lots in depot principal', () => {
+    browser.debugger();
```
Comment (jniles) [inline test/end-to-end/stock/stock.lots.spec.js]: Whoops.  :dancer:

File: client/src/modules/stock/adjustment/adjustment.html [hunk 10]
```diff
@@ -52,7 +72,7 @@
             class="form-control"
             name="description"
             ng-model="StockCtrl.movement.description"
-            placeholder="{{ ::'FORM.PLACEHOLDERS.DESCRIPTION' | translate }}"
+            placeholder="{{ 'FORM.PLACEHOLDERS.DESCRIPTION' | translate }}"
```
Comment (DedrickEnc) [inline client/src/modules/stock/adjustment/adjustment.html:75]: Why you remove it?

File: client/src/modules/stock/depot-selection.ctrl.js [hunk 11]
```diff
@@ -0,0 +1,59 @@
...
+      })
+      .catch(Notify.handleError)
+      .finally(toggleLoadingIndicator);
+  }
+
+  // fired when a user selects a depot from a list
+  function selectDepot(uuid) {
+    var selected;
+
+    vm.depots.forEach(function (d) {
```
Comment (DedrickEnc) [inline client/src/modules/stock/depot-selection.ctrl.js]: It seems like this can be performed by ```Array.filter``` like : 

```
var selected = vm.depots.filter(function (d) {
  return d.uuid === uuid;
}).pop();
```

Because we are sure to always match a depot with the provided ```uuid```

File: client/src/modules/stock/depot-selection.ctrl.js [hunk 12]
```diff
@@ -0,0 +1,59 @@
...
+function SelectDepotModalController(Instance, Depots, Notify, depot) {
+  var vm = this;
+
+  // bind the depot passed into the controller
+  vm.depot = depot;
+  vm.selectDepot = selectDepot;
+  vm.hasSelectedDepot = hasSelectedDepot;
+  vm.loading = false;
+
+  // this is a one-time message shown to the user if they do not have a cached depot.
```
Comment (DedrickEnc) [inline client/src/modules/stock/depot-selection.ctrl.js]: Where is the message? I think it is just a flag and the message is may be at the client side right?
If I am right, I think the comment should be updated.

File: client/src/modules/stock/depot-selection.modal.html [hunk 13]
```diff
@@ -0,0 +1,72 @@
...
+    </p>
+  </div>
+
+
+  <label class="control-label" translate>DEPOT.MODAL.SELECT_A_DEPOT</label>
+
+  <!-- list of depots -->
+  <ul class="list-group">
```
Comment (DedrickEnc) [inline client/src/modules/stock/depot-selection.modal.html:33]: What will happen if we have an institution with 10 depots ? the modal will still fit well in this situation? why not  to use select? (I like this user interface, I am just thinking in a laud voice).

File: client/src/modules/stock/entry/entry.html [hunk 14]
```diff
@@ -2,12 +2,32 @@
   <div class="bhima-title">
     <ol class="headercrumb">
       <li class="static" translate>TREE.STOCK</li>
-      <li class="title"><span translate>STOCK.ENTRY</span> <span class="text-uppercase badge badge-primary">{{StockCtrl.movement.entry_type}}</span></li>
+      <li ng-class="{ 'title' : !StockCtrl.depot.uuid, 'static' : StockCtrl.depot.uuid }">
+        <span translate>STOCK.ENTRY</span>
+      </li>
+
+      <li class="title" ng-if="StockCtrl.depot.uuid">
```
Comment (DedrickEnc) [inline client/src/modules/stock/entry/entry.html:9]: Why not ```StockCtrl.selectedDepot```?

File: client/src/modules/stock/entry/entry.js [hunk 15]
```diff
@@ -253,7 +261,32 @@ function StockEntryController(Depots, Inventory, Notify,
...
+      })
+      .then(function () {
+        vm.Stock.store.clear();
+        vm.movement = {};
+        ReceiptModal.stockEntryPurchaseReceipt(vm.document.uuid, bhConstants.flux.FROM_PURCHASE);
+      })
+      .catch(Notify.handleError);
+  }
+
+  /**
```
Comment (DedrickEnc) [inline client/src/modules/stock/entry/entry.js:279]: Good,  it will be better to precise what are ```data``` and ```uuid``` also in the comments as we have precision about function name, description and return statement

File: client/src/modules/stock/entry/entry.js [hunk 16]
```diff
@@ -3,45 +3,49 @@ angular.module('bhima.controllers')
...
 
   vm.Stock = new StockForm('StockEntry');
-  vm.depot = {};
   vm.movement = {};
 
   // bind methods
   vm.itemIncrement = 1;
   vm.enterprise = Session.enterprise;
   vm.maxLength = util.maxLength;
+  vm.maxDate = new Date();
```
Comment (DedrickEnc) [inline client/src/modules/stock/entry/entry.js:40]: It is seems like ```vm.maxDate``` is never used

File: client/src/modules/stock/exit/exit.js [hunk 17]
```diff
@@ -6,141 +6,124 @@ StockExitController.$inject = [
...
   vm.Stock = new StockForm('StockExit');
-  vm.depot = {};
   vm.movement = {};
 
   // bind methods
   vm.itemIncrement = 1;
-  vm.enterprise = Session.enterprise;
   vm.maxLength = util.maxLength;
+  vm.enterprise = Session.enterprise;
+  vm.maxDate = new Date();
```
Comment (DedrickEnc) [inline client/src/modules/stock/exit/exit.js:42]: is it used somewhere?

File: client/src/modules/stock/exit/exit.js [hunk 18]
```diff
@@ -6,141 +6,124 @@ StockExitController.$inject = [
...
 
   vm.gridOptions = gridOptions;
   vm.checkValidity = checkValidity;
 
-  // expose the API so that scrolling methods can be used
-  function onRegisterApi(api) {
-    vm.gridApi = api;
-  }
-
   // exit type
```
Comment (DedrickEnc) [inline client/src/modules/stock/exit/exit.js]: This comment tells almost nothing, I know it was there before this P.R

File: test/end-to-end/stock/stock.lots.spec.js (hunk 9 above)
Comment (DedrickEnc) [inline test/end-to-end/stock/stock.lots.spec.js]: ????

File: test/end-to-end/stock/stock.shared.page.js [hunk 19]
```diff
@@ -0,0 +1,59 @@
...
+  $(`[data-action="${action}"]`).click();
+}
+
+/**
+ * @function ensureModalIsOpen
+ *
+ * @description
+ * Makes sure that the modal is either already open or opens it.
+ *
+ * TODO(@jniles) This isn't great practice ... it probably should be re-examined
```
Comment (DedrickEnc) [inline test/end-to-end/stock/stock.shared.page.js:24]: LOL

**Review by DedrickEnc — COMMENTED** [review]
@jniles
I have made some minors comments, you can go a head fix them or clarify me and then the P.R should be ready to be merge in.

File: client/src/modules/stock/adjustment/adjustment.js (hunk 6 above)
Comment (DedrickEnc) [reply client/src/modules/stock/adjustment/adjustment.js]: hmmmm .... yes

File: client/src/modules/stock/adjustment/adjustment.html (hunk 10 above)
Comment (jniles) [reply client/src/modules/stock/adjustment/adjustment.html:75]: `::` is a one time binding.  It would bind the untranslated text in about 30% of the page loads for me.

File: client/src/modules/stock/depot-selection.ctrl.js (hunk 12 above)
Comment (jniles) [reply client/src/modules/stock/depot-selection.ctrl.js]: Ah, it is a boolean for showing the message.  The  message is actually in the HTML, hidden by an `ngIf` that listens on this variable.  The comment  could better describe this, I agree.

File: client/src/modules/stock/entry/entry.html (hunk 14 above)
Comment (jniles) [reply client/src/modules/stock/entry/entry.html:9]: I believe the previous version used `depot`, so I was attempting not to change the bindings too much :(.

File: client/src/modules/stock/entry/entry.js (hunk 16 above)
Comment (jniles) [reply client/src/modules/stock/entry/entry.js:40]: You are right!  It isn't ever used, but it should be - see https://github.com/IMA-WorldHealth/bhima-2.X/pull/2097 which fixes this in at least one module.

File: client/src/modules/stock/exit/exit.js (hunk 18 above)
Comment (jniles) [reply client/src/modules/stock/exit/exit.js]: Ha! :+1:

**Comment by jniles** [comment]
@dedrickenc, thanks for the thorough review.  I'll take a look at fixing these before the end of the day!

File: client/src/modules/stock/depot-selection.modal.html (hunk 13 above)
Comment (jniles) [reply client/src/modules/stock/depot-selection.modal.html:33]: In theory, there shouldn't be _too_ many depots.  But with more depots, it looks like this:

selectdepotwithatonofdepots
_Fig 1: Select depot with 14 depots_

**Comment by jniles** [comment]
Hmm... looks like Travis is still flaky.

**Comment by jniles** [comment]
@DedrickEnc changes have landed.

**Comment by DedrickEnc** [comment]
I am okay with the changes

**Review by DedrickEnc — APPROVED** [review]
LGTM

**Comment by jniles** [comment]
bors r+

.... try again.
