### PR TITLE
fix(journal): ensure col aggregates are displayed

### LINKED ISSUE #626: (bug) Posting Journal no longer aggregates debit/credit values
The Posting Journal used to display the balance of the debit/credit columns, but it no longer displays those aggregates.  This likely changed while migrating all the Posting Journal services to grid services

**Expected Result**: The column headers of each transaction group should contain the debits/credits for the transaction.

**Action Result**: See below.
nodebitcredits

### PR DESCRIPTION
**Pull request by jniles**
This commit ensures that the column aggregates for debits, credits, descriptions, and dates are shown on the grid group headers.  Because of careless cell template design, these values were not substituted into the templates in a previous iteration.

Closes #626.

---

Thank you for contributing!

Before submitting this pull request, please verify that you have:
- [x] Run your code through JSHint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
- [x] Run integration tests.
- [x] Run end-to-end tests.
- [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

File: client/src/js/components/bhInfo.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ angular.module('bhima.components')
       '  uib-popover-template="$ctrl.template" ' +
       '  popover-placement="right" ' +
       '  popover-append-to-body="true" ' +
-      '  popover-trigger="mouseenter"> ' +
+      '  popover-trigger="\'mouseenter\'"> ' +
```
Comment (jniles) [inline client/src/js/components/bhInfo.js:9]: ~~Whoops.  Didn't catch the unnecessary `\`~~.

File: client/src/js/services/grid/GridGrouping.js [hunk 2]
```diff
@@ -20,30 +20,45 @@ function GridGroupingService(uiGridGroupingConstants, $filter, Session, $timeout
...
   };
 
   /** @const aggregates quantities as needed */
-  var DEFAULT_QUANTITY_AGGREGATOR= {
+  var DEFAULT_QUANTITY_AGGREGATOR = {
     treeAggregationType : uiGridGroupingConstants.aggregation.SUM,
   };
 
+  /** @const aggregates by choosing a single item to display */
+  /** @todo - this currently defaults to MAX, should be implemented as it's own custom aggregator */
```
Comment (jniles) [inline client/src/js/services/grid/GridGrouping.js]: Hmm.. poor choice of English.
