### PR TITLE
fix(Receipt Modal for payslip)

### LINKED ISSUE #3722: Receipt modals display error when displaying the payslip
An error occurred when trying to display the pay statement because of the use ReceiptCtrl.document.posted

````
  <div
      id="receipt-confirm-posted"
      ng-if="ReceiptCtrl.document.posted"
      style="padding-top : 8px"
      class="pull-right">
    <span class="text-success">
      <span class="fa fa-check-circle-o"></span>
      <span translate>FORM.LABELS.POSTED</span>
    </span>
  </div>
````
This being not boot in the payroll function
This issue resolves this problem by adding the document property

### PR DESCRIPTION
**Pull request by lomamech**
- Adding property document in function payroll

closes #3722

### CODE REVIEW

**Comment by lomamech** [comment]
@jniles  @mbayopanda  I need a review

File: client/src/js/services/receipts/ReceiptModal.js [hunk 1]
```diff
@@ -257,6 +257,7 @@ function ReceiptModal(Modal, Receipts, Invoice, Cash, Voucher) {
       resolve : {
         receipt : function receiptProvider() { return { promise : payrollRequest }; },
         options : function optionsProvider() { return options; },
+        document : function documentProvider() { return {}; },
```
Comment (jniles) [inline client/src/js/services/receipts/ReceiptModal.js:260]: :+1:

**Review by jniles — APPROVED** [review]
Great bug fix.

bors r+
