### PR TITLE
fix(accounts): order transactions chronologically

### LINKED ISSUE #3868: Account Statement does not always render writings in chronological order
We received this bug report:

> For the "Rapport de compte simple" it would be necessary to have the
opportunity to put all the writings in a chronological order. We
talked about that. My statement for 2019 starts in the middel of may,
what is confusing.

It is clear that sometimes the account statement report doesn't render writings in chronological order.

Here is an example:
BugInAccountOrdering
_Nice that 11/05 comes before 1/05_

### PR DESCRIPTION
**Pull request by jniles**
Orders first by the transaction date, then by the creation date.

Closes #3868.

Proof:
FixedAccountOrdering

### CODE REVIEW

File: server/controllers/finance/accounts/transactions.js [hunk 1]
```diff
@@ -72,7 +72,7 @@ function getGeneralLedgerSQL(options) {
   `;
 
   filters.setGroup('GROUP BY record_uuid');
-  filters.setOrder('ORDER BY created_at ASC, trans_date ASC');
+  filters.setOrder('ORDER BY trans_date ASC, created_at ASC');
```
Comment (mbayopanda) [inline server/controllers/finance/accounts/transactions.js:75]: 👍

**Review by mbayopanda — APPROVED** [review]
LGTM 👍 

bors r+
