### PR TITLE
fix(xls): export XLS files without currency symbol

### LINKED ISSUE #3764: Do not render currency in MS Excel reports
For most reports, if a report is rendered in MS Excel, we should not render the currency symbol.  This will allow users to easily export to MS Excel, and sum the values in the report.  Ideally, this would be an option during the "Save as MS Excel" option.

### PR DESCRIPTION
**Pull request by jniles**
Implements a feature asked for by our clients to remove the currency symbol from the HTML -> Excel render.  This allows users to sum the numbers are ordinary values rather than parse the currency symbol.

Closes #3764.

### CODE REVIEW

File: server/lib/renderers/html.js [hunk 1]
```diff
@@ -39,14 +40,20 @@ function renderHTML(data, template, options = {}) {
...
   // factory code.
   const translate = translateHelperFactory(options.lang);
   hbs.helpers.translate = translate;
 
+  // NOTE(@jniles) - if the file is an XLS file that is being converted to
+  // excel, we don't do anything for the currency besides returning it.
+  if (options.skipCurrencyRendering) {
+    hbs.helpers.currency = finance.currencyWithoutSymbol;
+    hbs.helpers.debcred = finance.currencyWithoutSymbol;
+  }
```
Comment (mbayopanda) [inline server/lib/renderers/html.js:55]: 👍 😄

**Review by mbayopanda — APPROVED** [review]
