### PR TITLE
bug(Update Cost Center)

### LINKED ISSUE #5942: Problem in updating cost center data not related to cost_center_allocation_basis
The cost center updates interface does not display information for the cost center that is not linked to cost_center_allocation_basis

### PR DESCRIPTION
**Pull request by lomamech**
- Add close left join betwen cost_center and
  cost_center_allocation_basis

closes #5942

### CODE REVIEW

File: server/controllers/finance/cost_center.js [hunk 1]
```diff
@@ -17,7 +17,7 @@ async function lookupCostCenter(id) {
       cab.is_predefined AS allocation_basis_is_predefined,
       cabval.quantity AS allocation_basis_quantity
     FROM cost_center as fc
-    JOIN cost_center_allocation_basis as cab ON cab.id = fc.allocation_basis_id
+    LEFT JOIN cost_center_allocation_basis as cab ON cab.id = fc.allocation_basis_id
```
Comment (mbayopanda) [inline server/controllers/finance/cost_center.js:20]: 👍🏽

**Review by mbayopanda — APPROVED** [review]
LGTM 👍🏽
