### PR TITLE
(fix) Landing page 403

### LINKED ISSUE #1397: (bug) Fix error 403 on landing page detail when refresh
The new feature of the app on the main page throw error 403 when refresh the page.

How to reproduce : 
- Login into the page
- On the landing page click on the "click ici" button
landing_page

- After the click, the detail page is displayed
detail_page

- Refresh the page F5
error_detail

### PR DESCRIPTION
**Pull request by sfount**
This commit resolves the issue where the home details page would throw a
403 forbidden if it was ever independently routed to (page refreshed).It
adds the /landing/stats route to the exceptions for required tree
permissions.

It also refactors the layout to make this module seem part of the home
page as well as minor style adjustments to resolve broken UI.

**Details page as a child to the landing page**
screenshot 2017-03-27 at 14 56 29

Closes https://github.com/IMA-WorldHealth/bhima-2.X/issues/1397

### CODE REVIEW

File: client/src/js/app.js [hunk 1]
```diff
@@ -256,7 +259,7 @@ function startupConfig($rootScope, $state, $uibModalStack, SessionService, amMom
     var path = $location.path();
 
     var paths = SessionService.paths;
-    var publicRoutes = ['/', '/settings', '/login'];
+    var publicRoutes = ['/', '/settings', '/login', '/landing/stats'];
```
Comment (jniles) [inline client/src/js/app.js:262]: :+1:

File: client/src/partials/home/details.html [hunk 2]
```diff
@@ -1,23 +1,23 @@
 <div class="flex-header">
   <div class="bhima-title">
     <ol class="headercrumb">
-      <li class="static" translate>TREE.ADMIN</li>
+      <li class="static" style="text-transform : uppercase">{{ "HOME.BHIMA" | translate }}</li>
```
Comment (jniles) [inline client/src/partials/home/details.html]: You can use `class="text-uppercase"` for this to keep it bootstrapp-y.  Also, the `translate` filter is a regression.

File: client/src/partials/home/home.html [hunk 3]
```diff
@@ -20,7 +20,7 @@
                 {{ HomeCtrl.enterprise.name }}
               </div>
               <div class="uilabel">
-                <i class="fa fa-user"></i> {{ 'HOME.CONNECTED_USER' | translate }}: {{ HomeCtrl.user.display_name }} 
+                <i class="fa fa-user"></i> {{ 'HOME.CONNECTED_USER' | translate }}: {{ HomeCtrl.user.display_name }}
```
Comment (jniles) [inline client/src/partials/home/home.html]: Can you go ahead and use the `translate` directive here?

**Review by jniles — COMMENTED** [review]
I've made some comments to improve this.  A slight regression in the `translate` directive and some bootstrap instead of custom styles.

File: client/src/partials/home/home.html (hunk 3 above)
Comment (sfount) [reply client/src/partials/home/home.html]: Good catch - thanks for flagging these.

**Comment by jniles** [comment]
LGTM.
