### PR TITLE
bug(Profit and loss Report)

### LINKED ISSUE #5171: Bug Balance Sheet Report
there was a problem with the profit and lost (Compte de resultat) report, the introduction of period 13 did not take into account that the AccountReference.computeAllAccountReference malfunction when for a closed fiscal year the period referred to was the 13th and not the 12, but also due to the fact that period 13 does not have the end date, this disrupted the display of the Report

### PR DESCRIPTION
**Pull request by lomamech**
- Fix report for closed fiscal year
- Improve report display

closes #5171

### CODE REVIEW

File: server/controllers/finance/reports/ohada_profit_loss/index.js [hunk 1]
```diff
@@ -356,11 +356,14 @@ function getFiscalYearDetails(fiscalYearId) {
   // get fiscal year details and the last period id of the fiscal year
   const query = `
     SELECT
-      p.id AS period_id, p.end_date,
+      p.id AS period_id, fy.end_date,
       fy.id, fy.label, fy.previous_fiscal_year_id
     FROM fiscal_year fy
     JOIN period p ON p.fiscal_year_id = fy.id
-      AND p.number = (SELECT MAX(period.number) FROM period WHERE period.fiscal_year_id = ?)
+      AND p.number = (
```
Comment (jniles) [inline server/controllers/finance/reports/ohada_profit_loss/index.js:363]: This is the right solution :+1:

**Review by jniles — APPROVED** [review]
LGTM.  Great analysis and catch!

bors r+
