### PR TITLE
catch MySQL exception and rethrow with error in case of incorrect value

### LINKED ISSUE #4501: HTTP result codes different when running on MySQL 8 vs. 5.7
when sending a string to the API instead of a int in some cases the API responses with HTTP 404 on MySQL 5.7 and HTTP 400 on MySQL 8

see this discussion for details: https://github.com/IMA-WorldHealth/bhima/pull/4473#issuecomment-627096996

### PR DESCRIPTION
**Pull request by individual-it**
these changes make sure the HTTP return codes are the same on MySQL 5.7 & 8, when trying to request, update or delete a row but sending an invalid id type.

fixes #4501

Only tests have been added to endpoints where the tests have been changed in #4473, so endpoints or actions that have been untested before are still untested and might still react different on different versions on MySQL

### CODE REVIEW

File: server/controllers/payroll/accounts/index.js [hunk 1]
```diff
@@ -82,16 +82,23 @@ function update(req, res, next) {
...
+  const notFoundErrorMessage = `Could not find a Account Configuration with id ${req.params.id}`;
   db.exec(sql, [req.params.id])
     .then((row) => {
     // if nothing happened, let the client know via a 404 error
       if (row.affectedRows === 0) {
-        throw new NotFound(`Could not find a Account Configuration with id ${req.params.id}`);
+        throw new NotFound(notFoundErrorMessage);
       }
 
       res.status(204).json();
```
Comment (jeremielodi) [inline server/controllers/payroll/accounts/index.js]: You can change this ```res.status(204).json();``` to  ```res.sendStatus(204);``` if there is no json to send back

File: test/integration/accountConfig.js [hunk 2]
```diff
@@ -73,6 +73,14 @@ describe('(/payroll/account_configuration) The /payroll/account_configuration  A
       .catch(helpers.handler);
   });
 
+  it('DELETE /ACCOUNT_CONFIG/:ID will send back a 404 if the Account Configuration does receive a string instead of a number', () => {
+    return agent.delete('/account_config/str')
+      .then((res) => {
+        helpers.api.errored(res, 404);
```
Comment (jeremielodi) [inline test/integration/accountConfig.js:87]: 👍

**Review by jeremielodi — COMMENTED** [review]
@individual-it I propose to change ```deleteFromWhereId``` by just ```delete```  and you can pass the table name, the id key and value as parameters. This will help if we face the same issue with another table primary key whitch can be different to ```id```.

What do you think?

**Comment by individual-it** [comment]
@jeremielodi done, please review again

File: server/lib/db/index.js [hunk 3]
```diff
@@ -236,6 +236,27 @@ class DatabaseConnector {
   escape(key) {
     return mysql.escape(key);
   }
+
+  delete(table, idKey, idValue, res, next, notFoundErrorMessage) {
```
Comment (jeremielodi) [inline server/lib/db/index.js:240]: 👍

**Review by jeremielodi — APPROVED** [review]
@jeremielodi approve this PR. Well done @individual-it . Thanks
