### PR TITLE
Fixed issue with upload directories

### LINKED ISSUE #5207: UPLOAD_DIR doesn't seem to accept absolute paths
We're having a rather interesting bug in production where the UPLOAD_DIR doesn't accept absolute paths, but rather wants to make everything relative to the `client/` folder.  This isn't good.  We want to be able to set the absolute upload path to a place where future upgrades will not disturb it, particularly since upgrades can sometimes be destructive to the bin folder.

### PR DESCRIPTION
**Pull request by jmcameron**
Fix issue with upload directory always being under the bin directory.  Now it obeys the .env setting for UPLOAD_DIR.

**NOTES!**
- Only relative paths within the Bhima installation directory may be used
- Currently it will reject any absolute paths or paths that start with '..' for UPLOAD_DIR.
- Although it is probably possible to support absolute paths outside the Bhima installation, it will require updates to the app's 'app.use' function calls.  Without those changes, paths outside of the Bhima directory cannot be accessed via HTTPS calls without ENOENT errors.
- There are at least 3 ways to avoid conflicts with installation updates:
   - Create a new 'data' (or similar) directory inside the Bhima installation folder and add it to the .gitignore file.
   - Create a directory elsewhere and set up a symbolic/hard link to it within the Bhima directory
   - Revisit this issue and refactor to allow absolute paths.

**TESTING:**
- In your .env file, try changing UPLOAD_DIR to an absolute path and then a path beginning with '..'.  These should both fail.
   - NOTE that these failures are not handled very gracefully because this is an error that should be handled by the installer, not an end-user.
- Test the current default for the upload directory (eg, 'client/uploads'
   - Try uploading a file (eg in the Patient Registry, chose a patient and upload a document)
   - Verify the upload worked and the file is downloadable.  Do not delete it.
- Test in a new directory:
   - Use 'bhima_test' 
   - Create a folder within the Bhima installation directory (eg, 'data')
   - Change UPLOAD_DIR to the relative path for the new subdirectory the Bhima installation directory (eg, 'data').  
   - Enable the debugging option in .env:   DEBUG=app,errors,app:uploader
   - Monitor the client console for errors
   - Run 'yarn dev', notice in the server console the paths match what was given.  Also notice that it is NOT in the bin directory!
   - Try uploading a file (eg in the Patient Registry, chose a patient and upload a document)
   - Verify the upload worked and the file is downloadable
   - Delete the new file
   - Exit 'yarn dev' and delete the temporary upload folder
- Revert to the default UPLOAD directory (eg, 'client/uploads') and verify it still works and that the file uploaded earlier is still accessible.  Delete the file, if desired.
- Undo the debug settings in .env

### CODE REVIEW

File: server/lib/uploader.js [hunk 1]
```diff
@@ -35,17 +35,24 @@ const { uuid } = require('./util');
...
-const defaultDir = 'uploads'; // NOTE: this must be a relative path
-const dir = process.env.UPLOAD_DIR || defaultDir; // relative path
-const fsdir = path.join(process.cwd(), dir); // global path
+const defaultDir = 'uploads';
+const dir = process.env.UPLOAD_DIR || defaultDir;
+// NOTE: 'dir' must be a relative path (for http requests to work)
+if (path.isAbsolute(dir) || dir.startsWith('..')) {
+  throw new Error(`UPLOAD_DIR (${dir}) must be a relative path within the BHIMA software installation!`);
+}
+const rootDir = path.normalize(`${process.cwd()}/..`);
```
Comment (jniles) [inline server/lib/uploader.js]: This isn't guaranteed to be the root directory in all circumstances.  As explained in [this SO answer](https://stackoverflow.com/a/9874415), the `process.cwd()` is wherever the `node` call was made.  So, it can changed, depending on where the executing terminal is in the file system.

Instead, you probably want `__dirname`.   [Here is a really good tutorial explaining how it works](https://www.digitalocean.com/community/tutorials/nodejs-how-to-use__dirname).  This will never change, no matter who calls it or from where it is called.

**Comment by jniles** [comment]
Sorry about the force push 😞

**Comment by jniles** [comment]
Got it working.  Thanks so much for your help @jmcameron !

bors r+
