### PR TITLE
Fix (Research DebtorGroup)

### LINKED ISSUE #1715: Problem of the link between the list of debtor groups and patients
Problem with the link between the list of lending groups and the patients belonging to this group
imagg

### PR DESCRIPTION
**Pull request by lomamech**
Fix the link between the list of debtor groups and Patient
- Update the filter equals remove the alternative who check if there are a
  Default Uuid Partial Key
- Using db.convert for cash.debtor_uuid

closes #1715

### CODE REVIEW

File: server/controllers/finance/cash.js [hunk 1]
```diff
@@ -135,6 +135,8 @@ function read(req, res, next) {
  * @description list all payment made
  */
 function listPayment(options) {
+  // ensure epected options are parsed appropriately as binary
+  db.convert(options, ['debtor_uuid']);
```
Comment (jniles) [inline server/controllers/finance/cash.js:139]: I am sorry to say that I introduced this bug :(

Good catch!

**Review by jniles — APPROVED** [review]
